Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2020-09, with the labels that each got.

#128 📖 Add v1alpha4 note to readme
  README.md
Labels: approved, lgtm, size/XS

#129 🌱 Opt for a more inclusive Other PR category
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  VERSIONING.md
  hack/tools/release/notes.go
Labels: approved, lgtm, size/S

#131 🌱 Add Tilt setup for easier development
  .gitignore
  Makefile
  README.md
  Tiltfile
  docs/dev-setup.md
  examples/clusterctl-templates/clusterctl-cluster.yaml
  hack/ensure-kind.sh
  hack/gen_tilt_settings.sh
  hack/kind_with_registry.sh
  hack/kustomize-sub.sh
  hack/tools/go.mod
  hack/tools/go.sum
  tilt-provider.json
Labels: approved, lgtm, size/XL

#132 🌱 Tilt: Use external providers
  Makefile
  README.md
  Tiltfile
  docs/architecture.md
  docs/dev-setup.md
  docs/getting-started.md
  docs/releasing.md
  go.mod
  go.sum
  hack/gen_tilt_settings.sh
Labels: approved, lgtm, size/XL

#135 📖 Add note about node<--->bmh mapping after pivoting
  docs/getting-started.md
Labels: approved, lgtm, size/XS
