Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2020-10, with the labels that each got.

#134 ✨ Add Support for Ironic Basic auth in deployment templates
  config/bmo/kustomization.yaml
  config/bmo/secret_mount.yaml
  config/bmo/secrets.yaml
  config/default/namespace.yaml
  docs/getting-started.md
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/L

#133 ✨ Add support for TLS with custom CA certificate in BMO
  config/bmo/kustomization.yaml
  config/bmo/secret_mount.yaml
  config/default/namespace.yaml
  docs/getting-started.md
  hack/tools/install_kustomize.sh
Labels: approved, size/M

#136 🌱 Modify Metal3Machine association order
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#137 :sparkles: Adopt to BMO kubebuilder changes
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/suite_test.go
  config/bmo/bmo_image_patch.yaml
  config/bmo/bmo_pull_policy.yaml
  config/bmo/kustomization.yaml
  config/bmo/secret_mount.yaml
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, do-not-merge/hold, size/M

#138 :bug: Add missing namespace ironic configmap
  config/bmo/kustomization.yaml
Labels: approved, size/XS

#139 TLS and Basic auth vars for capm3 v0.4.1 release
  examples/clusterctl-templates/example_variables.rc
Labels: approved, lgtm, size/XS

#140 :bug: Fix incorrect variable in the doc
  docs/getting-started.md
Labels: approved, lgtm, size/XS

#141 🌱 Update golang to latest to match version across all repos
  Dockerfile
  Makefile
  Tiltfile
  go.mod
  hack/Dockerfile.unit
  hack/codegen.sh
  hack/ensure-go.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/govet.sh
  hack/tools/go.mod
Labels: approved, lgtm, size/S

#142 ✨ Add nodeDrainTimeout for example cluster template
  docs/getting-started.md
  examples/clusterctl-templates/clusterctl-cluster.yaml
  examples/controlplane/controlplane.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, lgtm, size/S

#143 🐛 Update dev-setup.md
  docs/dev-setup.md
Labels: approved, lgtm, size/XS

#144 🌱 Report v1a4 CI status in README
  README.md
Labels: approved, lgtm, size/XS
