Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2020-04, with the labels that each got.

#58 add tests for updateObj and createObj
  baremetal/metal3machine_manager_test.go
  go.sum
Labels: approved, lgtm, size/M

#66 :bug: CAPM3 should not select a BMH that is paused
  baremetal/metal3machine_manager.go
  go.sum
Labels: approved, lgtm, size/XS

#65 :bug: Fix small nits
  api/v1alpha2/doc.go
  api/v1alpha2/metal3machine_types.go
  api/v1alpha3/doc.go
  api/v1alpha3/metal3machine_types.go
  api/v1alpha4/doc.go
  api/v1alpha4/metal3machine_types.go
  baremetal/manager_factory_test.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3machine_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  docs/api.md
  docs/architecture.md
  docs/deployment_workflow.md
  docs/dev-setup.md
  examples/generate.sh
Labels: approved, lgtm, size/L

#67 :bug: CAPM3 should not select a BMH that is paused
  baremetal/metal3machine_manager.go
  go.sum
Labels: approved, lgtm, size/XS

#69 ⚠️ Introduce templating for metadata and network data
  Makefile
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/conversion.go
  api/v1alpha4/metal3data_types.go
  api/v1alpha4/metal3data_webhook.go
  api/v1alpha4/metal3data_webhook_test.go
  api/v1alpha4/metal3datatemplate_types.go
  api/v1alpha4/metal3datatemplate_webhook.go
  api/v1alpha4/metal3datatemplate_webhook_test.go
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  baremetal/manager_factory.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.manager_factory.go
  baremetal/mocks/zz_generated.metal3data_manager.go
  baremetal/mocks/zz_generated.metal3datatemplate_manager.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  baremetal/suite_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_metal3datas.yaml
  config/crd/patches/cainjection_in_metal3datatemplates.yaml
  config/crd/patches/webhook_in_metal3datas.yaml
  config/crd/patches/webhook_in_metal3datatemplates.yaml
  config/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
  docs/api.md
  docs/deployment_workflow.md
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
  examples/metal3crds/metal3.io_baremetalhosts.yaml
  examples/metal3plane/hosts.yaml
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XXL

#72 :bug: Fix provider name & version in clusterctl-setting
  clusterctl-settings.json
Labels: approved, lgtm, size/XS
