Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2020-07, with the labels that each got.

#110 🏃 Add fmuyassarov, furkatgofurov7, jan-est as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#111 🏃 Add fmuyassarov, furkatgofurov7, jan-est as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#108 🏃 Update Baremetal Operator for the new unmanaged state
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#109 🏃 Update Baremetal Operator for the new unmanaged state
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#113 🐛 Force deletion of BMH attributes when deleting m3m
  baremetal/metal3machine_manager.go
Labels: approved, lgtm, size/M

#114 🐛 Force deletion of BMH attributes when deleting m3m
  baremetal/metal3machine_manager.go
Labels: approved, lgtm, size/S

#117 :running: update baremetalhost crd to include boot mode field
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#115 :running: update baremetalhost crd to include boot mode field
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#118 :book: Fixes with naming in documentations
  docs/getting-started.md
  docs/images/components.png
Labels: approved, lgtm, size/XS

#119 🏃 Update namings in images
  docs/images/controllerssequencediagram.png
  docs/images/fields_mapping.png
Labels: approved, lgtm, size/XS

#121 🏃 Update dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#120 ✨ Adding support for dns servers in IPAM
  api/v1alpha4/metal3datatemplate_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  docs/api.md
Labels: approved, lgtm, size/L
