Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2020-03, with the labels that each got.

#4 ✨ Update BMO to latest version
  docs/deployment_workflow.md
  docs/releasing.md
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#6 :bug: Change shortnames to m3c and m3m
  api/v1alpha2/metal3cluster_types.go
  api/v1alpha2/metal3machine_types.go
  api/v1alpha3/metal3cluster_types.go
  api/v1alpha3/metal3machine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
Labels: approved, lgtm, size/S

#7 📖 Update documentation for release v1alpha3
  README.md
  docs/getting-started.md
Labels: approved, lgtm, size/S

#9 🏃 Change manager image tag to follow release-0.3 branch
  config/manager/manager_image_patch.yaml
Labels: approved, lgtm, size/XS

#11 :bug: Fix clusterctl-settings.json file
  clusterctl-settings.json
Labels: approved, lgtm, size/XS

#12 :bug: Fix Next version in clusterctl-settings.json
  clusterctl-settings.json
Labels: approved, lgtm, size/XS

#2 Add StateAvailable provision state
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3machine_controller_integration_test.go
Labels: approved, lgtm, ok-to-test, size/M

#14 :bug: Modify deploy-bmo-cr in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#20 :bug: Remove make install from Makefile
  Makefile
Labels: approved, lgtm, size/XS

#17 🐛 Add a requeue when getting a conflict on object update
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#18 🐛 Add a requeue when getting a conflict on object update
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#25 :bug: Fix bug in the order of BMH association
  baremetal/metal3machine_manager.go
Labels: approved, lgtm, size/S

#26 :bug: Fix bug in the order of BMH association
  baremetal/metal3machine_manager.go
Labels: approved, lgtm, size/S

#27 🐛 Fix the deletion step order and OwnerReference matching, add matchpolicy to webhooks
  api/v1alpha3/metal3cluster_webhook.go
  api/v1alpha3/metal3machineTemplate_webhook.go
  api/v1alpha3/metal3machine_webhook.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/remote/remote.go
  baremetal/utils.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/webhook/manifests.yaml
  controllers/metal3machine_controller_integration_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#28 🐛 Fix the deletion step order and OwnerReference matching, add matchpolicy to webhooks
  api/v1alpha4/metal3cluster_webhook.go
  api/v1alpha4/metal3machine_webhook.go
  api/v1alpha4/metal3machinetemplate_webhook.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/remote/remote.go
  baremetal/utils.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/webhook/manifests.yaml
  controllers/metal3machine_controller_integration_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#24 :sparkles: Set/Unset PauseAnnotation in BMH through CAPM3 machine + Tests
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#41 :bug: Fix Metal3ClusterToMetal3Machines function in metal3Machine Controller
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
  go.sum
Labels: approved, lgtm, size/L

#43 Fix Metal3ClusterToMetal3Machines function in metal3Machine Controller
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#32 🐛 Fix Namespace handling
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#31 🐛 Fix Namespace handling
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#49 🐛 PR fixes issue #48
  baremetal/metal3machine_manager.go
  controllers/metal3machine_controller.go
Labels: approved, lgtm, size/XS

#50 :bug: UpdateObject function should operate on a deepcopy of the object
  baremetal/metal3machine_manager.go
  go.sum
Labels: approved, lgtm, size/S

#52 :bug: UpdateObject function should operate on a deepcopy of the object
  baremetal/metal3machine_manager.go
Labels: approved, lgtm, size/XS

#53 :bug: Wrong contract labels for v1alpha4
  config/crd/kustomization.yaml
Labels: approved, lgtm, size/XS

#51 :bug: Multiple updates operation on the BMH #33
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#54 :bug: Multiple updates operation on the BMH #33
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, ok-to-test, size/M

#57 🐛This PR fixes issue #48
  baremetal/metal3machine_manager.go
  controllers/metal3machine_controller.go
Labels: approved, lgtm, size/XS

#61 🐛 Restrict host selection to ready or available hosts
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/S

#60 🐛Restrict host selection to ready or available hosts
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/S

#63 📖 Fix version in docs
  docs/api.md
  docs/architecture.md
Labels: approved, lgtm, size/M

#62 📖 Replace versions in docs
  docs/api.md
  docs/architecture.md
Labels: approved, lgtm, size/M
