Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2020-06, with the labels that each got.

#84 🐛 Use patch helper to update BMH
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/suite_test.go
  baremetal/utils.go
  baremetal/utils_test.go
Labels: approved, lgtm, size/L

#87 🐛 Update BMO dependency for root device hints
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#89 🐛 Use providerID when set on metal3machine
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#90 🐛 Use providerID when set on metal3machine
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#85 🏃 Remove code generation from unit test
  Makefile
  hack/codegen.sh
Labels: approved, lgtm, size/M, tide/merge-method-squash

#92 Add config support in codegen
  hack/codegen.sh
Labels: approved, lgtm, size/S

#68 ✨ Make BMO as part of CAPM3 deployment
  Makefile
  config/bmo/README.md
  config/bmo/bmo_image_patch.yaml
  config/bmo/kustomization.yaml
  config/bmo/kustomizeconfig.yaml
  config/kustomization.yaml
  docs/getting-started.md
  examples/clusterctl-templates/example_variables.rc
Labels: approved, lgtm, size/M

#94 🐛 Fix NPE when gateway is absent from IPPool
  baremetal/metal3data_manager.go
Labels: approved, lgtm, size/XS

#95 🏃 use gofmt -s to simplify the code
  api/v1alpha2/conversion.go
  api/v1alpha4/metal3datatemplate_webhook_test.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/utils_test.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#97 🐛 Fix bug when cluster is not found
  Makefile
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  examples/generate.sh
Labels: approved, lgtm, size/M

#98 🐛 Update IPAM dependency to bugfix release v0.0.3
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#86 🏃 initialize reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#93 initialize reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#96 ✨ PR prevents the use of BMH annotated as unhealthy
  api/v1alpha4/common_types.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/S

#100 🏃 Add BMO pull policy
  Makefile
  config/bmo/bmo_pull_policy.yaml
  config/bmo/kustomization.yaml
Labels: approved, lgtm, size/S

#102 ✨Add image disk format and checksum type
  api/v1alpha2/conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/common_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/utils_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3machine_controller_integration_test.go
  examples/clusterctl-templates/clusterctl-cluster.yaml
  examples/clusterctl-templates/example_variables.rc
  examples/metal3crds/metal3.io_baremetalhosts.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#103 🏃 Update v1a3 CRDs to add image checksum type and disk format
  api/v1alpha3/common_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/common_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: approved, lgtm, size/M

#101 🏃 Update config image patches and pull policy
  Makefile
  config/bmo/bmo_image_patch.yaml
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  config/ipam/pull_policy_patch.yaml
  go.mod
  go.sum
  hack/gofmt.sh
Labels: approved, lgtm, size/M

#105 🐛 Add an annotation with BMH status when pausing it
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/M

#106 ✨ Set Pause annotation on BMH when the cluster is paused
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/XL
