Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-10, with the labels that each got.

#307 ✨ Uplift controller runtime, controller-tools , CAPI, IPAM and BMO modules
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XL, approved, lgtm

#310 🐛 Fix CVE 2021-20329 and CVE-2021-32760
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#309 🌱 Update IPAM reference
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
Labels: size/XS, approved, lgtm

#291 🌱 Uplift golangci-lint in hack/tools/go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, lgtm, size/L

#293 🐛 Use the infrastructure components built by m3-dev-env
  hack/e2e/environment.sh
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting_test.go
Labels: size/S, approved, lgtm

#308 ✨ Automate releasing process with GitHub actions
  .github/workflows/release.yaml
  .gitignore
  Makefile
  hack/tools/release/notes.go
Labels: approved, lgtm, size/L

#312 🐛Upgrade containerd package to patched version to fix security vulnerability
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#313 🌱 Allow fetching repo tags when checking in GitHub Actions
  .github/workflows/release.yaml
Labels: size/XS, approved, lgtm

#323 🐛 Fix bug with missing checkout to a tag during releasing
  .github/workflows/release.yaml
  Makefile
Labels: size/XS, approved, lgtm

#267 :seedling: e2e node_reuse test
  go.mod
  go.sum
  hack/e2e/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/node_reuse_test.go
Labels: size/XL, approved, lgtm

#300 🌱Add an option to choose the cluster template from metal3-dev-env
  hack/e2e/environment.sh
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#340 :seedling: I'm not working directly on metal3 anymore.
  OWNERS
Labels: size/XS, approved, lgtm
