Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-05, with the labels that each got.

#202 🐛 Use consistent spelling for Ironic
  docs/architecture.md
  docs/deployment_workflow.md
  docs/dev-setup.md
  docs/getting-started.md
Labels: approved, lgtm

#201 Update instruction for using Tilt environment
  docs/dev-setup.md
Labels: approved, lgtm

#205 🌱 Update ipam config image patch and kustomization
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
Labels: approved, lgtm, size/XS

#206 :seedling: Uplift golangc-lint in hack/tools/go.mod
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/XXL

#204 🌱 Fix example manifests generation
  .gitignore
  Makefile
  examples/generate.sh
  examples/metal3plane/hosts.yaml
  examples/provider-components/image_versions_patch.yaml
  examples/provider-components/kustomization.yaml
  hack/ensure-kustomize.sh
Labels: approved, lgtm, size/L

#208 :seedling: Fix some typos
  api/v1alpha4/metal3machine_types.go
  baremetal/metal3cluster_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3labelsync_controller.go
Labels: approved, lgtm, ok-to-test, size/S

#210 🌱 Add rbac rules for MachineSets
  config/rbac/role.yaml
  controllers/metal3machine_controller.go
Labels: approved, lgtm, size/XS

#207 🌱 Add envsubst and gomock to hack/tools/go.mod
  .golangci.yaml
  baremetal/mocks/zz_generated.manager_factory.go
  baremetal/mocks/zz_generated.metal3cluster_manager.go
  baremetal/mocks/zz_generated.metal3data_manager.go
  baremetal/mocks/zz_generated.metal3datatemplate_manager.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  hack/gofmt.sh
  hack/golint.sh
  hack/govet.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/unit.sh
Labels: approved, lgtm, size/XXL

#194 🌱Add test with CAPI E2E testing framework
  Makefile
  docs/e2e-test.md
  go.mod
  go.sum
  hack/e2e/config_ubuntu.sh
  hack/ensure-kind.sh
  scripts/ci-e2e.sh
  templates/test/cluster-template-prow-ha.yaml
  templates/test/cluster-template-prow-single-master.yaml
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#215 :seedling: Uplift kube-rbac-proxy to v0.8.0
  config/manager/manager_auth_proxy_patch.yaml
Labels: approved, lgtm, size/XS

#216 🐛 Fix code duplication
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/XS

#214 🐛 Cleanup code duplication from data manager
  baremetal/metal3data_manager.go
Labels: approved, lgtm, size/XS

#209 :seedling: Fix gofmt warning: redundant type from array, slice, or map composite literal
  controllers/metal3labelsync_controller_test.go
Labels: approved, lgtm, ok-to-test

#189 ✨ Add live-iso support to CAPI Metal3 provider
  api/v1alpha4/common_types.go
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/metal3machine_types_test.go
  api/v1alpha4/metal3machine_webhook.go
  api/v1alpha4/metal3machine_webhook_test.go
  api/v1alpha4/metal3machinetemplate_webhook.go
  api/v1alpha4/metal3machinetemplate_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: approved, lgtm, ok-to-test, size/M

#200 📖 getting-started: clean up ironic bits
  docs/getting-started.md
Labels: approved, lgtm, size/S

#199 Remove secret generation of ironic CA cert in BMO.
  config/bmo/secrets.yaml
Labels: approved, lgtm, size/XS
