Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-01, with the labels that each got.

#151 📖 Fix typos in docs
  docs/getting-started.md
Labels: approved, lgtm, size/XS

#148 Fix typo in comment
  api/v1alpha4/metal3datatemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#153 :sparkles: Update go.mod
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL
