Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-04, with the labels that each got.

#184 Add templateReference logic in Metal3DataTemplate
  api/v1alpha4/metal3data_types.go
  api/v1alpha4/metal3data_webhook.go
  api/v1alpha4/metal3datatemplate_types.go
  baremetal/metal3datatemplate_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: approved, lgtm, size/M

#188 ✨ Install kustomize also in Mac OS.
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, ok-to-test, size/M

#152 ✨Adds a new controller to synchronize labels between BMHs and K Nodes
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3labelsync_controller.go
  controllers/metal3labelsync_controller_test.go
  main.go
Labels: approved, lgtm, ok-to-test, size/XL

#192 :sparkles: Add golint and generate test in travis
  .travis.yml
Labels: approved, lgtm, size/XS

#193 :sparkles: Uplift BMO in go.mod
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#195 🌱 Upgrade IPAM to v0.0.5
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#197 🐛 Fix bug that BMH NetworkData and MetaData cleaned on deprovisioning when they should not
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/M
