Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-06, with the labels that each got.

#220 🌱 Update go mod and image patch kustomization for the IPAM
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#221 🌱 Update go modules and image patch kustomization for the IPAM
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#226 Update reference to IPAM/api
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#227 ✨ Add Furkat and Anwar as approvers
  OWNERS
Labels: approved, lgtm, size/XS

#212 🌱 Use predefined BMH status in examples
  Makefile
  docs/dev-setup.md
  examples/controlplane/controlplane.yaml
  templates/test/cluster-template-prow-ha.yaml
  templates/test/cluster-template-prow-single-master.yaml
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/M

#223 ✨ Add BMO inject-ca-from custom patching
  config/bmo/bmo_inject_ca_patch.yaml
  config/bmo/bmo_patch_cert_dns.yaml
  config/bmo/kustomization.yaml
Labels: approved, lgtm, size/S

#229 Define makefile target for running ci-e2e.sh
  Makefile
  docs/e2e-test.md
  scripts/ci-e2e.sh
  templates/test/cluster-template-prow-ha.yaml
  templates/test/cluster-template-prow-single-master.yaml
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/M

#231 🌱 Update DockerHub registry path
  Dockerfile
  hack/Dockerfile.unit
  hack/codegen.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/govet.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
Labels: approved, lgtm, size/S

#230 Use predefined BMH status in examples (master)
  Makefile
  docs/dev-setup.md
  examples/controlplane/controlplane.yaml
Labels: approved, lgtm, size/S

#156 Allow disable automated cleaning
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/metal3machine_types.go
  baremetal/manager_factory.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/mocks/zz_generated.manager_factory.go
  baremetal/utils_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3machinetemplate_controller.go
  docs/api.md
  main.go
Labels: approved, lgtm, size/XL

#228 ⚠️ Remove v1alpha3 types
  Makefile
  README.md
  api/v1alpha3/common_types.go
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/doc.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha3/metal3cluster_types.go
  api/v1alpha3/metal3cluster_types_test.go
  api/v1alpha3/metal3machine_types.go
  api/v1alpha3/metal3machine_types_test.go
  api/v1alpha3/metal3machinetemplate_types.go
  api/v1alpha3/v1alpha3_suite_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/kustomization.yaml
  hack/codegen.sh
  main.go
  metadata.yaml
Labels: approved, lgtm, size/XXL

#234 🐛 Fix the CAMP3 api version in the e2e test framework
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm, size/S

#218 🌱E2E template parametrization
  .gitignore
  Makefile
  hack/e2e/config_ubuntu.sh
  hack/e2e/environment.sh
  scripts/ci-e2e.sh
  templates/test/cluster-template-prow-ha.yaml
  templates/test/cluster-template-prow-single-master.yaml
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/XL

#235 e2e: Adjust e2e tests to running in the CI
  hack/e2e/config_ubuntu.sh
  scripts/ci-e2e.sh
Labels: size/S
