Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-07, with the labels that each got.

#236 :seedling: remove dhellmann from owners
  OWNERS
Labels: approved, lgtm, size/XS

#240 ✨ Add conversion tests for v1alpha5 API
  api/v1alpha4/conversion_test.go
Labels: approved, lgtm, size/M

#243 🐛 Parameterize the CAPI and CAPM3 version in the e2e config file
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/S

#241 ✨ Use correct aliases for capm3 api
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/suite_test.go
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
  main.go
Labels: approved, lgtm, size/XXL

#239 ✨ Backport "Allow disable automated cleaning"
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/metal3machine_types.go
  baremetal/manager_factory.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/mocks/zz_generated.manager_factory.go
  baremetal/utils_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3machinetemplate_controller.go
  docs/api.md
  main.go
Labels: approved, lgtm, size/XL

#237 🌱Add generation of empty-ironic-cacert secret for handling TLS disabled scenario
  config/bmo/secrets.yaml
Labels: approved, lgtm, size/XS

#245 🌱 Drop Jaakko from the OWNERS list
  OWNERS
Labels: approved, lgtm, size/XS

#248 🌱 Sync OWNERS file between master and release-0.4 branches
  OWNERS
Labels: approved, lgtm, size/S

#247 🌱Add generation of empty-ironic-cacert secret for handling TLS disabled scenario(back port from master)
  config/bmo/secrets.yaml
Labels: approved, lgtm, size/XS

#249 🐛 Increase retry interval in label-sync controller to 30 seconds
  controllers/metal3labelsync_controller.go
Labels: approved, lgtm, ok-to-test, size/S

#242 ⚠️ Move BMO deployment from CAPM3
  Makefile
  config/bmo/README.md
  config/bmo/bmo_image_patch.yaml
  config/bmo/bmo_inject_ca_patch.yaml
  config/bmo/bmo_patch_cert_dns.yaml
  config/bmo/bmo_pull_policy_patch.yaml
  config/bmo/kustomization.yaml
  config/bmo/kustomizeconfig.yaml
  config/bmo/secret_mount_patch.yaml
  config/bmo/secrets.yaml
  config/kustomization.yaml
Labels: approved, lgtm, size/L

#256 📖 Update CI build status badges to use latest CAPM3 API version(v1alpha5)
  README.md
Labels: approved, lgtm, size/XS

#180 🌱 Set the UserAgent to "cluster-api-provider-metal3-manager"
  main.go
Labels: approved, lgtm, size/XS

#259 ✨ Add internal logging mechanism for e2e test framework
  test/e2e/internal/log/log.go
Labels: approved, lgtm, size/S

#261 ⚠️ Update IPAM controller image reference
  config/ipam/image_patch.yaml
Labels: approved, lgtm, size/XS
