Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-08, with the labels that each got.

#260 🐛 Add CAPI metadata.yaml to the e2e
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/v1alpha4/metadata.yaml
Labels: approved, lgtm, size/S

#263 ✨ Add BMO inject-ca-from custom patching
  config/bmo/bmo_inject_ca_patch.yaml
  config/bmo/bmo_patch_cert_dns.yaml
  config/bmo/kustomization.yaml
Labels: size/S, approved, lgtm

#224 ✨Implement externally managed annotation
  controllers/metal3cluster_controller.go
Labels: size/S, approved, lgtm

#254 ✨Update example generation and docs with latest CAPI v1a4 changes
  Makefile
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  docs/api.md
  docs/dev-setup.md
  examples/cluster/cluster.yaml
  examples/cluster/kustomizeconfig.yaml
  examples/clusterctl-templates/clusterctl-cluster.yaml
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeconfig.yaml
  examples/generate.sh
  examples/machinedeployment/kustomizeconfig.yaml
  examples/machinedeployment/machinedeployment.yaml
  examples/metal3plane/hosts.yaml
  examples/provider-components/image_versions_patch.yaml
  go.sum
Labels: size/XL, approved, lgtm

#262 🌱 Don't use v1beta1 APIs of CRD
  examples/metal3crds/metal3.io_baremetalhosts.yaml
Labels: size/XS, approved, lgtm

#271 🐛 Fix the cloud-init in the centos template
  templates/test/cluster-template-prow-ha-centos.yaml
Labels: size/XS, approved, lgtm

#275 ✨ Align flag names with k8s components
  main.go
Labels: approved, lgtm, size/M

#274 📖 Extend releasing document
  docs/releasing.md
Labels: size/S, approved, lgtm

#276 ✨ Uplift CAPI to 0.4.2 in go.mod
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#278 🐛 Webhook reg should accept both v1 and v1beta1 admissions
  api/v1alpha5/metal3cluster_webhook.go
  api/v1alpha5/metal3data_webhook.go
  api/v1alpha5/metal3dataclaim_webhook.go
  api/v1alpha5/metal3datatemplate_webhook.go
  api/v1alpha5/metal3machine_webhook.go
  api/v1alpha5/metal3machinetemplate_webhook.go
  config/webhook/manifests.yaml
Labels: approved, lgtm, size/M

#279 ✨ Add webhook readiness and health check
  main.go
Labels: size/XS, approved, lgtm
