Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-12, with the labels that each got.

#414 🌱 Don't update BMH automatedCleaningMode if it is set to nil in M3M
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/utils_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: approved, lgtm, size/M

#421 🐛 Fix wrong capi api version mentions in api folder
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
Labels: size/S, approved, lgtm

#419 🌱 Add smoshiur1237 as reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#424 🐛 Require image-spec v1.0.2
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#423 🐛 Require image-spec v1.0.2
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#415 ✨ Rework node reuse logic to handle corner cases
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#390 🐛 Fix node reuse test workflow in E2E
  test/e2e/cert_rotation_test.go
  test/e2e/common.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/M

#408 🐛Fix node reuse workflow in E2E in release-0.5 branch
  test/e2e/cert_rotation_test.go
  test/e2e/common.go
  test/e2e/e2e_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#420 🐛 Remove unnecessary and buggy step in e2e remediation test
  test/e2e/remediation_test.go
Labels: size/S, approved, lgtm

#409 Fix the flaky issue with cert-rotation
  test/e2e/cert_rotation_test.go
Labels: approved, lgtm, size/M

#354 :seedling: Introduce re-pivoting e2e test
  hack/e2e/environment.sh
  test/e2e/cert_rotation_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#397 🌱 Increase unit test converage for metal3labelsync controller
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#388 🌱 Backport re-pivoting e2e test
  hack/e2e/environment.sh
  test/e2e/cert_rotation_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#431 🐛 Automated cleaning bug fix in machine template controller
  baremetal/metal3machinetemplate_manager.go
Labels: size/XS, approved, lgtm

#430 🌱 Bump code-generator to v0.23.0
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#433 ✨ Uplift golang 1.17 in capm3-unit image
  hack/Dockerfile.unit
Labels: size/XS, approved, lgtm

#404 🌱 Add unit tests for remediation controller
  controllers/metal3remediation_controller.go
  controllers/metal3remediation_controller_test.go
Labels: approved, lgtm, size/L

#384 ⚠️ Default LeaderElectionResourceLock to leases
  config/rbac/leader_election_role.yaml
  main.go
Labels: approved, lgtm, size/M

#428 🐛 Fix CAPI release fetching for Tilt environment
  Tiltfile
  docs/dev-setup.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
  tilt_modules/cert_manager/Tiltfile
Labels: size/S, approved, lgtm

#336 :seedling: E2e upgrade ironic test
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/upgrade_ironic_test.go
Labels: approved, lgtm, size/M

#434 ✨Add E2E upgrade ironic test to release-0.5 branch
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/upgrade_ironic_test.go
Labels: approved, lgtm, size/M

#441 🌱 Use golang image as base for unit test containers
  hack/unit.sh
Labels: size/XS, approved, lgtm

#429 ✨ Uplift go 1.17 , CAPI v1.0.2 and controller-runtime to v0.11.0-beta.0.0.20211110210527-619e6b92dab9
  .github/workflows/release.yaml
  Dockerfile
  Tiltfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/codegen.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/govet.sh
  hack/tools/go.mod
  hack/tools/tools.go
Labels: size/XL, approved, lgtm

#436 🌱 Use golang image as base for unit test containers
  hack/unit.sh
Labels: size/XS, approved, lgtm

#437 🌱 Drop capm3:unit container image Dockerfile
  hack/Dockerfile.unit
Labels: size/XS, approved, lgtm

#439 🌱Use golang image as base for unit test containers
  hack/unit.sh
Labels: size/XS, approved, lgtm

#442 🌱Bump controller-runtime to v0.11.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#446 🌱Add unit tests for m3 machine template controller
  Makefile
  baremetal/mocks/zz_generated.metal3machinetemplate_manager.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#447 🐛 Fix upgrading mariadb container in upgrade ironic e2e tests
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/upgrade_ironic_test.go
Labels: size/S, approved, lgtm

#445 ⚠️ Uplift CAPI to prerelease v1.1.0-beta.1
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#448 ✨ Fix clusterctl init issue and failing upgrade ironic containers tests in E2E
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting_test.go
  test/e2e/upgrade_ironic_test.go
Labels: approved, lgtm, size/L

#356 🌱Cover upgrade test requirements in node reuse e2e tests
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse_test.go
Labels: approved, lgtm, size/L

#450 ✨ Update master reference to main/controlplane and BMO reference to main branch
  README.md
  VERSIONING.md
  docs/dev-setup.md
  docs/releasing.md
  hack/e2e/environment.sh
Labels: size/S, approved, lgtm

#452 📖 Introduce trigger phrases for e2e test in README
  README.md
Labels: size/S, approved, lgtm
