Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-09, with the labels that each got.

#280 ✨ Uplift controller tools to v0.6.2
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#277 Fix e2e calico configuration and BMO installation workflow
  go.mod
  go.sum
  test/e2e/common.go
  test/e2e/e2e_test.go
  test/e2e/pivoting_test.go
  test/e2e/yaml.go
Labels: approved, lgtm, size/L

#269 🐛 Fix Metal3MachineTemplate log output
  baremetal/metal3machinetemplate_manager.go
Labels: ok-to-test, size/XS, approved, lgtm

#265 Add cert-rotation e2e test
  test/e2e/cert_rotation_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/internal/log/log.go
  test/e2e/pivoting_test.go
Labels: approved, lgtm, size/L

#272 Restore the BMO config map and add more logs to the e2e pivoting test
  test/e2e/common.go
  test/e2e/pivoting_test.go
Labels: size/S, approved, lgtm

#282 🐛 Fix the problem that "scale in" operation does not work after e2e pivoting
  test/e2e/pivoting_test.go
Labels: size/XS, approved, lgtm

#284 🌱 Add namnx228 to the reviewers list
  OWNERS
Labels: size/XS, approved, lgtm

#287 🌱 Remove deprecated ioutil usage
  test/e2e/common.go
  test/e2e/pivoting_test.go
Labels: size/XS, approved, lgtm

#286 🌱 Parameterize API versions in e2e templates
  templates/test/cluster-template-prow-ha-centos.yaml
  templates/test/cluster-template-prow-ha.yaml
Labels: approved, lgtm, size/M

#270 📖update architecture doc per current output
  docs/architecture.md
Labels: ok-to-test, approved, lgtm, size/M

#285 🌱 Uplift controller runtime
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#289 ✨ Add AGE column to metal3 CRDs
  api/v1alpha5/metal3cluster_types.go
  api/v1alpha5/metal3data_types.go
  api/v1alpha5/metal3dataclaim_types.go
  api/v1alpha5/metal3datatemplate_types.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/metal3machinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: approved, lgtm, size/M

#292 Fix e2e tests
  templates/test/cluster-template-prow-ha-centos.yaml
  templates/test/cluster-template-prow-ha.yaml
  test/e2e/e2e_test.go
Labels: size/S, lgtm

#296 Remove travis ci config file
  .travis.yml
Labels: approved, lgtm

#295 ✨ Remove 'run' make target
  Makefile
  examples/generate.sh
  examples/metal3crds/metal3.io_baremetalhosts.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm

#299 Expose the parameter of libvirt VM number used by e2e tests
  hack/e2e/environment.sh
Labels: size/XS, approved, lgtm

#297 🐛 Remove capm3- prefix from root kustomize
  config/default/capm3/kustomization.yaml
  config/default/kustomization.yaml
Labels: size/XS, approved, lgtm

#298 🐛 Remove capm3- prefix from root kustomize
  config/bmo/kustomization.yaml
  config/default/kustomization.yaml
  config/kustomization.yaml
  config/webhook/kustomization.yaml
Labels: size/XS, approved, lgtm

#305 Update tilt configuration
  Tiltfile
  hack/gen_tilt_settings.sh
  tilt_modules/cert_manager/Tiltfile
Labels: size/S, approved, lgtm

#303 Delete the container Ironic-inspector-watch-log from the e2e test
  test/e2e/e2e_test.go
  test/e2e/pivoting_test.go
Labels: size/S, approved, lgtm
