Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-03, with the labels that each got.

#162 🌱 Install cert-manager with extension
  Tiltfile
  tilt_modules/cert_manager/README.md
  tilt_modules/cert_manager/Tiltfile
  tilt_modules/extensions.json
Labels: approved, lgtm, size/L

#161 🌱 Bump the Golang version to 1.16
  Dockerfile
  Tiltfile
  go.mod
  hack/Dockerfile.unit
  hack/codegen.sh
  hack/gofmt.sh
  hack/golint.sh
  hack/govet.sh
Labels: approved, lgtm, size/S

#171 🌱 Update kind & kubectl & k8s & CAPI versions
  Tiltfile
  controllers/suite_test.go
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/fetch_ext_bins.sh
Labels: approved, lgtm, size/XS

#172 🌱 Use errors.Errorf() instead of fmt.Errorf()
  api/v1alpha3/metal3cluster_types.go
  api/v1alpha3/metal3machine_types.go
  api/v1alpha4/metal3cluster_types.go
  api/v1alpha4/metal3machine_types.go
  baremetal/metal3machine_manager.go
Labels: approved, lgtm, size/S

#173 🌱 reorder OWNERS alphabetically
  OWNERS
Labels: approved, lgtm, size/S

#175 🌱Add more shortNames for metal3 config objects
  api/v1alpha2/metal3cluster_types.go
  api/v1alpha2/metal3machine_types.go
  api/v1alpha2/metal3machinetemplate_types.go
  api/v1alpha3/metal3cluster_types.go
  api/v1alpha3/metal3machine_types.go
  api/v1alpha3/metal3machinetemplate_types.go
  api/v1alpha4/metal3cluster_types.go
  api/v1alpha4/metal3data_types.go
  api/v1alpha4/metal3dataclaim_types.go
  api/v1alpha4/metal3datatemplate_types.go
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/metal3machinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: approved, lgtm, ok-to-test, size/M

#181 :sparkles: Update Essential tooling for CAPM3
  api/v1alpha4/metal3cluster_webhook.go
  api/v1alpha4/metal3data_webhook.go
  api/v1alpha4/metal3dataclaim_webhook.go
  api/v1alpha4/metal3datatemplate_webhook.go
  api/v1alpha4/metal3machine_webhook.go
  api/v1alpha4/metal3machinetemplate_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/webhook/manifests.yaml
  config/webhook/webhookcainjection_patch.yaml
  examples/addons.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/XXL

#182 🐛 Fix error message in m3dt webhook
  api/v1alpha4/metal3datatemplate_webhook.go
Labels: approved, lgtm, size/XS

#164 ⚠️ Remove v1alpha2 types
  Makefile
  README.md
  api/v1alpha2/common_types.go
  api/v1alpha2/conversion.go
  api/v1alpha2/conversion_test.go
  api/v1alpha2/doc.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/metal3cluster_types.go
  api/v1alpha2/metal3cluster_types_test.go
  api/v1alpha2/metal3cluster_webhook.go
  api/v1alpha2/metal3clusterlist_webhook.go
  api/v1alpha2/metal3machine_types.go
  api/v1alpha2/metal3machine_types_test.go
  api/v1alpha2/metal3machine_webhook.go
  api/v1alpha2/metal3machinelist_webhook.go
  api/v1alpha2/metal3machinetemplate_types.go
  api/v1alpha2/metal3machinetemplate_webhook.go
  api/v1alpha2/metal3machinetemplatelist_webhook.go
  api/v1alpha2/v1alpha2_suite_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/kustomization.yaml
  hack/codegen.sh
  main.go
  metadata.yaml
Labels: approved, lgtm, size/XXL

#183 🌱 Use explicit path for conversion-gen output
  Makefile
Labels: approved, lgtm, size/XS

#186 🌱 Update template for bug reporting
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, size/XS

#187 📖 fix name of vlanID field in API documentation
  docs/api.md
Labels: approved, lgtm, size/XS

#147 Fix incorrect use of variable kb_root_dir
  hack/fetch_ext_bins.sh
Labels: approved, lgtm, ok-to-test, size/S
