Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2021-11, with the labels that each got.

#355 Separate bmh crd and crs deployment in Tilt environment
  Makefile
Labels: size/S, approved, lgtm

#345 🐛 Fix node_reuse and remediation flakiness
  hack/e2e/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#359 🌱 Fix an outdated URL in README.md
  README.md
Labels: ok-to-test, size/XS, approved, lgtm

#341 ✨ Bump clusterctl metadata to v1beta1
  metadata.yaml
Labels: size/XS, approved, lgtm

#352 ⚠️ Adapt CAPM3 to CAPI v1beta1
  README.md
  Tiltfile
  api/go.mod
  api/go.sum
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/manager_factory.go
  baremetal/manager_factory_test.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3remediation_manager.go
  baremetal/metal3remediation_manager_test.go
  baremetal/mocks/zz_generated.manager_factory.go
  baremetal/mocks/zz_generated.metal3datatemplate_manager.go
  baremetal/mocks/zz_generated.metal3remediation_manager.go
  baremetal/remote/remote.go
  baremetal/remote/remote_test.go
  baremetal/suite_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3cluster_controller.go
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/e2e/environment.sh
  main.go
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
Labels: size/XXL, approved, lgtm

#371 ✨ Uplift bmo/api to v0.0.0-20211105090508-c38de6aabf99
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#365 🐛 Fix flaky issues on node reuse remediation tests
  hack/e2e/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#363 Remove vulnerable import k8s.io/kubernetes v1.13.0
  go.mod
  go.sum
  test/e2e/node_reuse_test.go
Labels: approved, lgtm, size/M

#364 🐛 Remove vulnerable import k8s.io/kubernetes v1.13.0
  go.mod
  go.sum
  test/e2e/node_reuse_test.go
Labels: approved, lgtm, size/M

#361 🌱 Audit v1beta1 APIs to follow CAPI conventions
  api/v1beta1/common_types.go
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3data_types.go
  api/v1beta1/metal3dataclaim_types.go
  api/v1beta1/metal3datatemplate_types.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machinetemplate_types.go
  api/v1beta1/metal3remediation_types.go
  api/v1beta1/metal3remediationtemplate_types.go
Labels: approved, lgtm, size/L

#379 📖 Fix a typo in docs/api.md
  docs/api.md
Labels: ok-to-test, size/XS, approved, lgtm

#378 📖 Add pivoting and provider installation instructions
  README.md
Labels: approved, lgtm, size/M

#377 📖 Add pivoting and provider installation instructions
  README.md
Labels: approved, lgtm, size/M

#370 🐛 Use proper infrastructure var in e2e conf
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#366 🌱 Remove omitempty fields and add optional tag to some status fields in v1beta1 types.
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3data_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
Labels: size/S, approved, lgtm

#381 ✨ Uplift/controller runtime v0.10.3 and cluster-api to v1.0.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#382 ✨ Update IPAM image reference
  config/ipam/image_patch.yaml
Labels: size/XS, approved, lgtm

#374 🌱 Add description to m3cluster NoCloudProvider boolean field
  api/v1alpha4/metal3cluster_types.go
  api/v1alpha5/metal3cluster_types.go
  api/v1beta1/metal3cluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
Labels: size/S, approved, lgtm

#368 🌱 Add a function to retrieve nodes using labels
  baremetal/metal3machine_manager.go
Labels: size/S, approved, lgtm

#376 ✨Update generate example files according latest CAPI v1beta1
  examples/cluster/cluster.yaml
  examples/cluster/kustomizeconfig.yaml
  examples/clusterctl-templates/clusterctl-cluster.yaml
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeconfig.yaml
  examples/generate.sh
  examples/machinedeployment/kustomizeconfig.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, lgtm, size/M

#387 ✨ Uplift sigs.k8s.io/cluster-api/test to v1.0.1
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#389 🌱 Refactor test scripts
  .gitignore
  Makefile
  hack/fetch_ext_bins.sh
  hack/tools/install_kubebuilder.sh
  hack/unit.sh
Labels: approved, lgtm, size/M

#394 🐛 Use v0.5.x tag for manager image in release-0.5 images
  config/default/capm3/manager_image_patch.yaml
Labels: size/XS, approved, lgtm

#375 🌱Use providerID and providerLabel prefixes
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/M

#369 ✨ Add providerID in m3mdata
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/suite_test.go
Labels: approved, lgtm, size/M

#360 🌱 parameterize providerID parts in tests
  baremetal/metal3machine_manager_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/M

#399 🐛 Uplift github.com/containerd/containerd v1.5.8
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#403 🐛 Uplift github.com/containerd/containerd v1.5.8
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#395 🌱 Ensure setting image tag for current release in infra components
  Makefile
Labels: size/XS, approved, lgtm

#407 Fix the flaky issue with cert-rotation
  test/e2e/cert_rotation_test.go
Labels: approved, lgtm, size/M

#362 📖 Add Remediation Controller documentations to CAPM3
  docs/remediation-controller.md
Labels: approved, lgtm, size/L

#411 🌱 Don't update BMH automatedCleaningMode if it is set to nil in M3M
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/zz_generated.deepcopy.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/utils_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: approved, lgtm, size/M

#393 Fix the kcp issue in e2e test
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm
