Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-10, with the labels that each got.

#714 🌱 Refactor e2e tests and add more logs
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/inspection_test.go
  test/e2e/live_iso_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/remediation_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XXL, approved, lgtm

#752 🌱 E2e: fix upgrade, don't print cluster template
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XS, approved, lgtm

#753 🌱 E2e: Don't print CRs in target cluster when running ephemeral test
  test/e2e/pivoting_based_feature_test.go
Labels: size/XS, approved, lgtm

#598 🌱 Reuse capi upgrade test function
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#761 🐛 Fix overriding OS env var from Makefile
  Makefile
Labels: size/XS, approved, lgtm

#757 🌱 Bump golang to v1.18 and related changes
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Tiltfile
  api/go.mod
  api/go.sum
  docs/architecture.md
  go.mod
  go.sum
  hack/codegen.sh
  hack/ensure-golangci-lint.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/unit.sh
  test/e2e/common.go
Labels: size/XL, approved, lgtm

#759 🐛 Dump target cluster resources before repivoting
  test/e2e/pivoting_based_feature_test.go
Labels: size/S, approved, lgtm

#764 🌱 Uplift capi to v1.2.4
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#766 🌱 Uplift go modules to fix CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#755 🌱 Bump k8s version v1.25.2, cert-manager v1.9.1, calico v3.24.1
  Tiltfile
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/M

#767 🌱 Fix Kubebuilder Assets export (source is not working in darwin)
  Makefile
Labels: size/XS, approved, lgtm

#770 🌱 Uplift go modules to fix CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#768 🌱 Uplift go modules to fix CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#771 🌱 Bump cert-manager to v1.10.0 in Tiltfile and script
  Tiltfile
  hack/gen_tilt_settings.sh
Labels: size/XS, approved, lgtm
