Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-04, with the labels that each got.

#584 📖 Update Versioning notes
  VERSIONING.md
Labels: approved, lgtm, size/M

#561 🐛 Fix mockgen path in tools.go
  hack/tools/tools.go
Labels: size/XS, approved, lgtm

#586 🐛 Fix condition Reasons values for Metal3Machine
  api/v1beta1/condition_consts.go
Labels: size/XS, approved, lgtm

#595 🌱 Upgrade to controller-runtime v0.11.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#596 🌱 Backport: Add unit test to m3 machine template controller
  Makefile
  api/v1alpha5/metal3machine_types.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/mocks/zz_generated.metal3machinetemplate_manager.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#597 🌱 Add and update unit tests for metal3remediation manager.
  baremetal/metal3remediation_manager_test.go
Labels: approved, lgtm, size/L

#519 :seedling: Improve logging of Data creation
  baremetal/metal3data_manager.go
Labels: ok-to-test, approved, lgtm, size/M

#559 🌱 Unify provider and baremetal operator imports in the codebase
  .golangci.yaml
  baremetal/manager_factory.go
  baremetal/manager_factory_test.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/metal3remediation_manager.go
  baremetal/metal3remediation_manager_test.go
  baremetal/suite_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3cluster_controller.go
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/metal3remediation_controller.go
  controllers/metal3remediation_controller_test.go
  controllers/suite_test.go
  main.go
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/inspection_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XXL, approved, lgtm

#545 🌱 Expand unit tests for node reuse feature in Delete function
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#594 🐛 Patch instead of update when setting the node providerID
  baremetal/metal3machine_manager.go
Labels: size/S, approved, lgtm

#602 :seedling: Increase judgment to avoid panic
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#603 :book: Fix an outdated link in dev-setup.md
  docs/dev-setup.md
Labels: size/XS, approved, lgtm

#601 :seedling: Add judgment before output log
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#600 🌱 Rearrange e2e upgrade tests
  scripts/environment.sh
  test/e2e/e2e_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/S, approved, lgtm

#609 :seedling: Modify the error message in createSecrets
  baremetal/metal3data_manager.go
Labels: size/XS, approved, lgtm

#608 :seedling: Fix nil point error in metal3remediation_manager
  baremetal/metal3remediation_manager.go
  baremetal/metal3remediation_manager_test.go
Labels: size/S, approved, lgtm

#572 🌱 Improve e2e structure
  Makefile
  docs/e2e-test.md
  test/e2e/common.go
  test/e2e/e2e_test.go
  test/e2e/pivoting_based_feature_tests.go
  test/e2e/remediation_feature_test.go
  test/e2e/remediation_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XXL, approved, lgtm

#610 🌱 Update cert-manager to v1.7.2
  Tiltfile
  examples/generate.sh
  hack/gen_tilt_settings.sh
Labels: size/XS, approved, lgtm

#606 :seedling: Add test case to descendantsTestCases
  baremetal/metal3cluster_manager_test.go
Labels: size/S, approved, lgtm

#605 🌱 Add host nil log info to machine manager Delete function
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#612 🌱 Add CentOS stream 9 in e2e test scripts
  scripts/environment.sh
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm
