Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-07, with the labels that each got.

#654 🌱 Use ginkgo focus instead of boolean
  Makefile
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#661 📖 Synchronize OWNERS file with main branch
  OWNERS
Labels: size/XS, approved, lgtm

#655 :seedling: fix error panic
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#659 🌱 Uplift k8s version to 1.23.8 and cluster api to v1.1.5
  README.md
  api/go.mod
  api/go.sum
  docs/api.md
  docs/dev-setup.md
  examples/generate.sh
  go.mod
  go.sum
  hack/fetch_ext_bins.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/L

#620 🌱 Add live ISO e2e test
  docs/e2e-test.md
  scripts/ci-e2e.sh
  test/e2e/live_iso_test.go
Labels: approved, lgtm, size/M

#663 📖 Update trigger phrases with new changes in CI
  README.md
Labels: size/S, approved, lgtm

#667 🐛 Live ISO cleanup fix
  test/e2e/live_iso_test.go
Labels: approved, lgtm, size/M

#670 🐛 Fix remediation cleanup
  baremetal/metal3remediation_manager.go
  controllers/metal3remediation_controller.go
  test/e2e/metal3remediation_test.go
Labels: ok-to-test, approved, lgtm, size/M

#615 🌱 Uplift k8s to 1.24.1 and support new control plane taint
  config/manager/manager.yaml
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  docs/remediation-controller.md
  examples/addons.yaml
  examples/generate.sh
  examples/provider-components/manager_tolerations_patch.yaml
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/M
