Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-02, with the labels that each got.

#487 :seedling: Standardize controller & baremetal unit test syntax
  baremetal/manager_factory_test.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/metal3remediation_manager_test.go
  baremetal/utils_test.go
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/metal3remediation_controller_test.go
Labels: size/XL, approved, lgtm

#497 ✨ Uplift controller-tools to v0.8.0 and uplift cluster-api to v1.1.0-rc.0
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting_test.go
Labels: approved, lgtm, size/L

#499 ✨ Add LogFolder parameter in e2e for collecting kind logs
  test/e2e/e2e_suite_test.go
Labels: size/XS, approved, lgtm

#502 ✨ Uplift CAPI to v1.1.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting_test.go
Labels: approved, lgtm, size/M

#503 ✨ Uplift IPAM, CAPI to v0.4.7 in release-0.5 branch
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#486 ✨ Add BMO upgrade e2e test
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_test.go
  test/e2e/upgrade_baremetal_operator_test.go
  test/e2e/upgrade_ironic_test.go
Labels: approved, lgtm, size/M

#504 🌱 Use CAPI v1.1.0 in tilt settings
  hack/gen_tilt_settings.sh
Labels: size/XS, approved, lgtm

#426 🌱Add test entries for metal3machine manager and manager_factory
  baremetal/manager_factory_test.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#505 ✨ Update CI badges and artifactory image path with metal3
  README.md
  test/e2e/node_reuse_test.go
Labels: size/XS, approved, lgtm

#507 ✨ Update CI badges and artifactory image path with metal3
  README.md
Labels: size/XS, approved, lgtm

#506 ✨ Update CI badges and artifactory image path with metal3
  README.md
  test/e2e/node_reuse_test.go
Labels: size/XS, approved, lgtm

#494 📖 Add instruction for accessing tilt dashboard remotely and locally
  docs/dev-setup.md
Labels: size/XS, approved, lgtm

#512 🌱 Add 1.1 release series in metadata.yaml
  metadata.yaml
Labels: size/XS, approved, lgtm

#513 :seedling: Remove jan as an active reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#511 🌱 Remove install_kustomize.sh under hack/tools and use ensure_kustomize.sh from hack folder
  Makefile
  docs/dev-setup.md
  hack/ensure-kustomize.sh
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/M

#516 ✨ Uplift BMO module in go.mod
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#515 🌱 Update e2e metadata, CAPI modules and e2e configuration with v1.1.1
  api/go.mod
  api/go.sum
  clusterctl-settings.json
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: approved, lgtm, size/M

#518 Add fmuyassarov as an approver
  OWNERS
Labels: size/XS, approved, lgtm

#517 🐛 Reconcile Metal3MachineTemplate on Metal3Machine events
  controllers/metal3machinetemplate_controller.go
Labels: approved, lgtm, size/M

#521 🐛 Uplift docker/distribution to v2.8.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#488 ✨ Allow Capm3 Fast Track in bmh when AutomatedCleaning is enabled
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  controllers/metal3machine_controller_integration_test.go
Labels: approved, lgtm, size/L

#524 🐛 Fix IMAGE_OS case
  hack/e2e/environment.sh
Labels: size/XS, approved, lgtm

#529 🐛Cherrypick live-iso option to Image's DiskFormat for v1a5 in release-0.5
  api/v1alpha5/common_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: size/XS, approved, lgtm

#527 🐛 Add live-iso option to Image's DiskFormat in v1a5 and v1b1
  api/v1alpha5/common_types.go
  api/v1beta1/common_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: size/XS, approved, lgtm

#532 ✨ Uplift CAPI to v1.1.2 and controller runtime to v0.11.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#514 ✨ [Part1] Add golangci lint yaml
  .golangci.yaml
  baremetal/manager_factory.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3remediation_manager.go
  baremetal/requeue_error.go
  baremetal/suite_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3cluster_controller.go
  controllers/metal3data_controller.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3labelsync_controller.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3remediation_controller.go
  controllers/metal3remediation_controller_test.go
  controllers/suite_test.go
  main.go
  test/e2e/cert_rotation_test.go
  test/e2e/common.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
  test/e2e/yaml.go
Labels: size/XL, approved, lgtm

#533 🌱 Replace jetstack from cert-manager URL and update version to v1.5.3
  examples/generate.sh
  tilt_modules/cert_manager/README.md
  tilt_modules/cert_manager/Tiltfile
Labels: size/XS, approved, lgtm

#525 🌱 Allow GA releases to trigger on v* tags
  .github/workflows/release.yaml
Labels: size/XS, approved, lgtm

#520 🐛 Reconcile Metal3MachineTemplate on Metal3Machine events
  controllers/metal3machinetemplate_controller.go
Labels: approved, lgtm, size/M

#531 🌱 Update IPAM to latest in go modules, config image patch and kustomization files
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#536 📖 Update ubuntu based e2e tests trigger phrases
  README.md
Labels: size/XS, approved, lgtm

#538 🌱 Uplift e2e test module to v1.1.2 in go mod and e2e conf file
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
Labels: size/S, approved, lgtm

#509 ⚠️ Drop CAPM3 v1alpha4 support from main branch
  Makefile
  README.md
  api/v1alpha4/common_types.go
  api/v1alpha4/conversion.go
  api/v1alpha4/conversion_test.go
  api/v1alpha4/doc.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/metal3cluster_types.go
  api/v1alpha4/metal3cluster_types_test.go
  api/v1alpha4/metal3data_types.go
  api/v1alpha4/metal3dataclaim_types.go
  api/v1alpha4/metal3datatemplate_types.go
  api/v1alpha4/metal3machine_types.go
  api/v1alpha4/metal3machine_types_test.go
  api/v1alpha4/metal3machinetemplate_types.go
  api/v1alpha4/metal3remediation_types.go
  api/v1alpha4/metal3remediationtemplate_types.go
  api/v1alpha4/v1alpha4_suite_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  config/crd/kustomization.yaml
  docs/api.md
  hack/codegen.sh
  main.go
  metadata.yaml
Labels: size/XXL, approved, lgtm

#540 🌱 Add unit tests for metal3MachineTemplate reconciliation
  api/v1beta1/metal3machine_types.go
  baremetal/metal3machinetemplate_manager_test.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3machinetemplate_controller_test.go
Labels: approved, lgtm, size/L

#534 🌱 Remove tilt_modules
  Tiltfile
  tilt_modules/cert_manager/README.md
  tilt_modules/cert_manager/Tiltfile
  tilt_modules/cert_manager/test/Tiltfile
  tilt_modules/cert_manager/test/test.sh
  tilt_modules/extensions.json
Labels: approved, lgtm, size/L

#541 📖 Update root README file
  README.md
Labels: approved, lgtm, size/M
