Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-11, with the labels that each got.

#775 :seedling: Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: size/S, approved, lgtm

#777 🌱 Uplift CAPI to v1.2.5
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#778 🌱 Uplift CAPI to v1.2.5
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#780 🌱 Uplift IPAM to v1.2.1 and BMO to v0.1.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#781 🌱 Fix PREVIOUS_TAG fetching in release-notes Makefile target
  Makefile
Labels: size/S, approved, lgtm

#782 🐛 Fix body_path in the release.yaml
  .github/workflows/release.yaml
Labels: size/XS, approved, lgtm

#784 🌱 build: introduce support for FROM overrides
  Dockerfile
Labels: ok-to-test, size/XS, approved, lgtm

#788 🌱 Improve release automation process
  .github/workflows/release.yaml
  Makefile
Labels: size/S, approved, lgtm

#756 📖 Add IP reuse documentation
  docs/ip_reuse.md
Labels: approved, lgtm, size/M

#790 🐛 Fix running e2e upgrade tests with pre-releases
  test/e2e/data/infrastructure-metal3/v1beta1/metadata.yaml
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#772 🌱 remove ginkgo failFast when running e2e tests
  Makefile
Labels: size/XS, approved, lgtm

#762 🌱 Use latest k8s version instead of previous minor version for e2e tests
  scripts/environment.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#792 🌱 Uplift CAPI to v1.2.6
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#791 🌱 Uplift CAPI to v1.3.0-rc.0 in main branch
  Makefile
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/gen_tilt_settings.sh
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#783 🌱 Add SkipCRDNamePreflightCheckAnnotation to Metal3Data CRD
  config/crd/kustomization.yaml
  config/crd/patches/skipcrdnamecheck_in_metal3datas.yaml
Labels: size/S, approved, lgtm
