Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-12, with the labels that each got.

#728 🌱 Refactor e2e: Remove test suffix from function files and use function inputs instead of global vars
  test/e2e/cert_rotation.go
  test/e2e/common.go
  test/e2e/inspection.go
  test/e2e/metal3remediation.go
  test/e2e/node_reuse.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_baremetal_operator.go
  test/e2e/upgrade_ironic.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XXL, approved, lgtm

#794 🌱 Remove test suffix from pivoting function file
  test/e2e/pivoting.go
Labels: size/XS, approved, lgtm

#796 🌱 Uplift CAPI to v1.3.0
  CONTRIBUTING.md
  README.md
  api/go.mod
  api/go.sum
  docs/disk_cleaning.md
  docs/ip_reuse.md
  docs/releasing.md
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#797 🐛hack: download latest CAPI for tilt
  hack/gen_tilt_settings.sh
Labels: size/XS, approved, lgtm

#799 🌱 Ginkgo v2: Use --show-node-events parameter instead of --progress
  Makefile
Labels: size/XS, approved, lgtm

#802 🌱 Uplift BMO and IPAM in go modules and config/
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#803 Bump mdl to 0.12.0 and pin it to sha:digest
  hack/markdownlint.sh
Labels: size/XS, approved, lgtm

#801 🌱 Add release 1.3 branch/release related changes
  Makefile
  README.md
Labels: size/S, approved, lgtm

#807 🌱 shellcheck: pin to 0.9.0
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm

#809 🌱 Bump CAPI to v1.3.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm

#810 🐛 uplift x/net to 0.4.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#813 🐛 uplift x/net to 0.4.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#814 🐛 uplift x/net to 0.4.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#817 🌱 Bump CAPI to v1.2.8
  CONTRIBUTING.md
  README.md
  api/go.mod
  api/go.sum
  docs/disk_cleaning.md
  docs/releasing.md
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#818 🌱 Bump CAPI to v1.3.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#821 Add default Metal3DataTemplate to example
  examples/clusterctl-templates/clusterctl-cluster.yaml
Labels: size/S, ok-to-test, approved, lgtm

#811 🌱 Bump upgraded k8s version and add basic logging after e2e tests
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3cluster_controller_test.go
  scripts/environment.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
Labels: approved, lgtm, size/L
