Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-09, with the labels that each got.

#704 🌱 Don't remove ownerRef from IPClaim when deleting
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: size/S, approved, lgtm

#710 🌱 Update owners file to move inactive approvers/reviewers to emeritus and add Lennart as a reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#703 🐛 Use keyfile format for CentOS network config
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Labels: approved, lgtm, size/L

#711 🐛 Use keyfile format for CentOS network config
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Labels: approved, lgtm, size/L

#712 Uplift ubuntu to 22.04
  docs/api.md
  examples/generate.sh
  scripts/environment.sh
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#707 :book: Document Versioning in contributing guide
  CONTRIBUTING.md
  VERSIONING.md
Labels: approved, lgtm, size/L

#656 ✨ Support IP Reuse for BMHs using Preallocations
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/utils.go
  config/manager/manager.yaml
  main.go
Labels: approved, lgtm, size/L

#709 🌱 Improve handling of IPClaims with deletion timestamp
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/suite_test.go
Labels: approved, lgtm, size/M

#693 🐛 fix Image validation requiring urls for checksum
  api/v1beta1/common_types.go
  api/v1beta1/common_types_test.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machine_types_test.go
  api/v1beta1/metal3machine_webhook.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: ok-to-test, approved, lgtm, size/L

#721 🌱 sync OWNER file with main
  OWNERS
Labels: size/XS, approved, lgtm

#687 🐛 Fix missing LACP bond mode
  api/v1beta1/metal3datatemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: ok-to-test, size/XS, approved, lgtm

#722 🐛 Fix BMOBRANCH fetching in e2e by sourcing lib/releases from dev env
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#716 🌱 Uplift ubuntu to 22.04
  docs/api.md
  examples/generate.sh
  scripts/environment.sh
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#715 🌱 Uplift Ubuntu to 22.04
  docs/api.md
  examples/generate.sh
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#731 🌱 Bump dependencies: CAPI to v1.1.6, IPAM to v1.1.4 and BMO to v0.1.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  hack/gomod.sh
Labels: approved, lgtm, size/L

#718 🌱 Bump dependencies: CAPI v1.2.2 , BMO v0.1.1, IPAM v1.2.0 and downgrade k8s modules to v0.24.2 to match CAPI release-1.2
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#729 🐛 Fix e2e waiting for status
  test/e2e/inspection_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#733 🐛 Fix dev-env templates path
  docs/api.md
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#730 📖 Note new release-1.2 branch e2e test triggers in readme
  README.md
Labels: size/S, approved, lgtm

#732 🐛 Image validation requiring urls for checksum
  api/v1beta1/common_types.go
  api/v1beta1/common_types_test.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machine_types_test.go
  api/v1beta1/metal3machine_webhook.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: ok-to-test, approved, lgtm, size/L

#734 🌱 Bump dependencies in hack/tools to match CAPI 1.2 release branch
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#737 🌱 Update release process
  docs/releasing.md
  hack/tools/release/notes.go
Labels: approved, lgtm, size/M

#739 📖 Update README with latest CAPM3/CAPI release references
  README.md
Labels: size/S, approved, lgtm

#741 🌱 Add v1.2 CAPI release contract to e2e metadata file
  hack/gen_tilt_settings.sh
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: size/S, approved, lgtm

#681 🌱 Add v1.2 CAPI release contract to e2e metadata file
  hack/gen_tilt_settings.sh
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: size/S, approved, lgtm

#742 🐛Fix missing metadata contract for infrastructure-metal3 and update next-version for cluserterctl
  clusterctl-settings.json
  test/e2e/data/infrastructure-metal3/v1beta1/metadata.yaml
Labels: size/XS, approved, lgtm

#744 🐛 Remediation: fix nil panic when setting unhealthy annotation on host
  baremetal/metal3remediation_manager.go
Labels: ok-to-test, size/XS, approved, lgtm

#745 🌱 Install CNI with ClusterResourceSet
  scripts/environment.sh
  test/e2e/data/infrastructure-metal3/bases/cluster/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/crs.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/kustomization.yaml
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/M

#749 Prameterize api version for ClusterResourceSet
  test/e2e/data/infrastructure-metal3/bases/cluster/crs.yaml
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XS, approved, lgtm
