Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-08, with the labels that each got.

#675 :bug: Fix overlapping providerID duplicate detection
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#618 :seedling: Improve the verification of Image
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machine_types_test.go
Labels: size/S, approved, lgtm

#676 :bug: Fix initial target cluster K8s version
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#674 🌱Uplift capi to v1.2
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  controllers/metal3cluster_controller.go
  controllers/suite_test.go
  examples/metal3crds/metal3.io_baremetalhosts.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
Labels: size/XXL, approved, lgtm

#679 🐛 Don't use IPClaims with deletion timestamp
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/M

#684 🌱 Update metadata to include capi 1.2.X releases
  metadata.yaml
Labels: size/XS, approved, lgtm

#690 🐛Only use redfish-virtualmedia for live-iso test
  scripts/ci-e2e.sh
  test/e2e/live_iso_test.go
Labels: size/S, approved, lgtm

#691 🌱 Move fmuyassarov to emeritus_approvers
  OWNERS
Labels: size/XS, approved, lgtm

#678 🌱 share logic between ip address allocation and release
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: ok-to-test, size/XL, approved, lgtm

#694 🐛Only use redfish-virtualmedia for live-iso test (backport)
  test/e2e/live_iso_test.go
Labels: size/XS, approved, lgtm

#685 🌱 Use finalizer on IPClaim to avoid premature deletion
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  controllers/metal3data_controller.go
Labels: approved, lgtm, size/M

#699 🌱 Add Adil as reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#698 🌱 Run linter also on api folder
  Makefile
  api/v1alpha5/common_types.go
  api/v1alpha5/groupversion_info.go
  api/v1alpha5/metal3cluster_types.go
  api/v1alpha5/metal3data_types.go
  api/v1alpha5/metal3dataclaim_types.go
  api/v1alpha5/metal3datatemplate_types.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/metal3machinetemplate_types.go
  api/v1alpha5/metal3remediation_types.go
  api/v1alpha5/metal3remediationtemplate_types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1beta1/common_types.go
  api/v1beta1/condition_consts.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3cluster_webhook.go
  api/v1beta1/metal3data_types.go
  api/v1beta1/metal3data_webhook.go
  api/v1beta1/metal3data_webhook_test.go
  api/v1beta1/metal3dataclaim_types.go
  api/v1beta1/metal3dataclaim_webhook.go
  api/v1beta1/metal3dataclaim_webhook_test.go
  api/v1beta1/metal3datatemplate_types.go
  api/v1beta1/metal3datatemplate_webhook.go
  api/v1beta1/metal3datatemplate_webhook_test.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machine_webhook.go
  api/v1beta1/metal3machinetemplate_types.go
  api/v1beta1/metal3machinetemplate_webhook.go
  api/v1beta1/metal3remediation_types.go
  api/v1beta1/metal3remediation_webhook.go
  api/v1beta1/metal3remediationtemplate_types.go
  api/v1beta1/metal3remediationtemplate_webhook.go
  api/v1beta1/metal3remediationtemplate_webhook_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
Labels: size/XL, approved, lgtm

#701 🌱 Revert API breaking change
  api/v1alpha5/metal3datatemplate_types.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1beta1/metal3datatemplate_types.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/M

#700 🐛 Fix clusterctl config file path
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting_test.go
Labels: size/XS, approved, lgtm
