Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-06, with the labels that each got.

#634 🌱 Uplift CAPI modules to v0.4.8 in release-0.5 branch
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#633 🌱 Uplift CAPI to v1.1.4 in main branch
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#636 🐛 Fix e2e pivoting by adding capi labels on hardware data crd
  test/e2e/pivoting_test.go
Labels: size/S, approved, lgtm

#632 🌱 Add dead link linter github workflow
  .github/workflows/lint-docs.yaml
  .markdownlinkcheck.json
  docs/dev-setup.md
  docs/releasing.md
Labels: approved, lgtm, size/M

#619 :seedling: fix ControlPlaneEndpoint in metal3cluster_manager
  baremetal/metal3cluster_manager.go
  baremetal/metal3cluster_manager_test.go
Labels: size/XS, approved, lgtm

#638 📖 Add parallel e2e triggers to the README
  README.md
Labels: size/XS, approved, lgtm

#639 🌱 Improve logging in machine manager
  baremetal/metal3machine_manager.go
  baremetal/metal3remediation_manager.go
  controllers/metal3data_controller.go
  controllers/metal3labelsync_controller.go
Labels: ok-to-test, approved, lgtm, size/M

#637 Make e2e ginkgo fail fast
  Makefile
Labels: size/XS, approved, lgtm

#642 🌱 Add zhouhao3 as a reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#643 🐛 Downgrade ubuntu to 20.04 in e2e tests to fix ironic/bmo communication
  docs/api.md
  examples/generate.sh
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#645 🌱 Uplift IPAM to v1.1.3, BMO to latest and docker/distribution to v2.8.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#566 :bug: Fix recursion in deleteOwnerRefFromList
  baremetal/metal3machine_manager.go
Labels: ok-to-test, size/XS, approved, lgtm

#644 🐛 Move dev-env cleaning to the makefile so it get triggered from the pipeline cleaning stage
  Makefile
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#583 🌱 Leave BMO and Ironic configmaps alone
  test/e2e/pivoting_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M
