Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-05, with the labels that each got.

#562 🐛 Fix choose host function unit tests
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#581 Define ObjectMeta `metav1.ObjectMeta` at Test case level
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/metal3remediation_manager_test.go
  baremetal/suite_test.go
  baremetal/utils_test.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/suite_test.go
Labels: size/XL, approved, lgtm

#604 :seedling: Add url validation to the subfield of image
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machine_types_test.go
  controllers/metal3machine_controller_integration_test.go
Labels: approved, lgtm, size/M

#614 :seedling: Add Centos 9 support for release-0.5 branch e2e test
  hack/e2e/environment.sh
  test/e2e/node_reuse_test.go
Labels: size/XS, approved, lgtm

#587 Define ObjectMeta metav1.ObjectMeta at Test case level for baremetal package tests
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/suite_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/M

#599 🌱 e2e conf parameterization
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/M

#621 🐛 Fix pivoting based e2e test file name
  test/e2e/pivoting_based_feature_test.go
Labels: ok-to-test, size/XS, approved, lgtm

#617 Change hard coded object names and uuids
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3remediation_manager_test.go
  baremetal/suite_test.go
  baremetal/utils_test.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/suite_test.go
Labels: size/XXL, approved, lgtm

#626 🌱 Introduce Ubuntu 22.04 related changes for v1alpha5
  Tiltfile
  docs/api.md
  docs/dev-setup.md
  examples/generate.sh
  hack/e2e/environment.sh
  hack/fetch_ext_bins.sh
  hack/gen_tilt_settings.sh
  test/e2e/node_reuse_test.go
Labels: approved, lgtm, size/M

#625 🌱 Introduce Ubuntu 22.04 related changes
  docs/api.md
  examples/generate.sh
  scripts/environment.sh
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#624 🐛 Handle node search based on label even when bmhID of providerID is overriden.
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#628 🌱 Name CI test badges correctly
  README.md
Labels: size/XS, approved, lgtm

#629 🌱 Add kubesec for CAPM3
  .github/workflows/kubesec.yml
  template/sarif.tpl
Labels: approved, lgtm, size/L

#611 🌱 Add kubesec for CAPM3
  .github/workflows/kubesec.yml
  template/sarif.tpl
Labels: do-not-merge/hold, approved, lgtm, size/L

#631 🐛 Uplift to gopkg.in/yaml to v3.0.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, approved, lgtm

#573 🌱 Don't write hardware details into statusAnnotation
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: size/S, approved, lgtm
