Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-03, with the labels that each got.

#491 Remove providerID field from m3mdata
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/suite_test.go
Labels: approved, lgtm, size/M

#539 🐛 Replace update taints with patch node taints
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#537 🌱 Generate templates from e2e
  Makefile
  config/default/kustomization.yaml
  scripts/ci-e2e.sh
  templates/test/cluster-template-prow-ha-centos.yaml
  templates/test/cluster-template-prow-ha.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/md.yaml
  test/e2e/data/infrastructure-metal3/bases/ippool/ippool.yaml
  test/e2e/data/infrastructure-metal3/bases/ippool/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-centos/controlplane-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-centos/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-centos/workers-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-ubuntu/controlplane-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-ubuntu/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-ubuntu/workers-kubeadm-config.yaml
  test/e2e/e2e_test.go
Labels: size/XXL, approved, lgtm

#522 ✨ [Part2] Add more linters into golangci.yml
  .golangci.yaml
  api/v1alpha5/metal3machine_types.go
  api/v1beta1/metal3machine_types.go
  baremetal/manager_factory.go
  baremetal/manager_factory_test.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager.go
  baremetal/metal3remediation_manager.go
  baremetal/metal3remediation_manager_test.go
  baremetal/remote/remote.go
  baremetal/remote/remote_test.go
  baremetal/suite_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3cluster_controller.go
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/suite_test.go
  main.go
  test/e2e/common.go
  test/e2e/e2e_test.go
  test/e2e/inspection_test.go
  test/e2e/node_reuse_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
  test/e2e/upgrade_baremetal_operator_test.go
  test/e2e/yaml.go
Labels: size/XXL, approved, lgtm

#551 🌱 Uplift containerd CRI plugin
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#549 🌱Parameterize namespace name in tests
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3remediation_manager_test.go
  baremetal/suite_test.go
  baremetal/utils_test.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#544 :book: Add creation of BMO namespace in root README instructions
  README.md
Labels: ok-to-test, size/XS, approved, lgtm

#548 Add providerid field metadata
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/suite_test.go
Labels: size/S, approved, lgtm

#466 🌱 Add v1alpha5 to v1beta e2e upgrade tests
  Makefile
  hack/e2e/environment.sh
  scripts/ci-e2e.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-centos/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-centos/workers-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-ubuntu/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-ubuntu/workers-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-upgrade-workload/kustomization.yaml
  test/e2e/data/infrastructure-metal3/v1alpha5/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1beta1/metadata.yaml
  test/e2e/data/shared/v1alpha4/metadata.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/pivoting_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/XL, approved, lgtm

#554 📖 Synchronize OWNERS file in release-0.5 branch with main
  OWNERS
Labels: size/S, approved, lgtm

#556 🌱 Change dev-env default branch from master to main in e2e script
  docs/api.md
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#555 🌱 Remove hardys from OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#547 🌱 Introduce gosec file for go security checks and related changes
  .golangci.yaml
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  hack/gosec.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/common.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#558 🌱 Uplift CAPI version in e2e tests to 1.1.3 and 0.4.8 and CAPI go modules to 1.1.3
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/e2e/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/M

#552 :seedling: Allow kubectl caching after cluster creation
  docs/api.md
  docs/getting-started.md
  examples/clusterctl-templates/example_variables.rc
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Labels: ok-to-test, size/XS, approved, lgtm

#560 Fix bmhID parsing when providerid is set on the node directly.
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#553 📖 Document e2e tests
  README.md
  docs/e2e-test.md
Labels: approved, lgtm, size/M

#567 🌱 Add gosec file and related changes in release-0.5 branch
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  hack/gosec.sh
  test/e2e/common.go
Labels: approved, lgtm, size/M

#568 🌱Add e2e tests for ephemeral cluster
  Makefile
  scripts/ci-e2e.sh
  test/e2e/cert_rotation_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/node_reuse_test.go
  test/e2e/upgrade_baremetal_operator_test.go
  test/e2e/upgrade_ironic_test.go
Labels: approved, lgtm, size/L

#571 🌱 Add concurrency parameter in gosec
  hack/gosec.sh
Labels: size/XS, approved, lgtm

#574 🐛Fix node reuse test for e2e ephemeral cluster tests
  test/e2e/node_reuse_test.go
Labels: size/XS, approved, lgtm

#576 ✨ Uplift BMO modules to latest (March 2022)
  go.mod
  go.sum
  hack/tools/go.mod
Labels: size/XS, approved, lgtm

#577 🌱 Remove golint linter from golangci.yaml and rename golint hack script to golangci-lint
  .golangci.yaml
  hack/ensure-golangci-lint.sh
Labels: size/S, approved, lgtm

#563 ✨ Introduce an additional providerID format and set providerID from nodes when noCloudProvider is set to false
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  baremetal/suite_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#579 🌱 Uplift IPAM in gomod and kustomize files
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#585 🌱 Uplift CAPM3 version to v1.1.1
  README.md
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#578 Uplift k8s to 1.23.5
  docs/api.md
  docs/dev-setup.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
Labels: size/S, approved, lgtm

#550 ✨ Reduce e2e test dependencies on dev-env
  Makefile
  hack/e2e/environment.sh
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/cert_rotation_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/pivoting_test.go
  test/e2e/remediation_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#582 🌱 Add namespace to test case object names
  controllers/suite_test.go
Labels: size/S, approved, lgtm
