Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2022-01, with the labels that each got.

#385 ✨ Use grouping feature of Tilt to add CAPM3 label
  Tiltfile
  tilt-provider.json
Labels: approved, lgtm, size/M

#456 🐛Rename unused BMH state mentions in e2e tests
  test/e2e/remediation_test.go
Labels: size/XS, approved, lgtm

#459 🌱Remove static calico files from E2E tests
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/cni/calico/calico-centos.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: size/XXL, approved, lgtm

#457 🌱 Uplift to github.com/docker/docker v20.10.11
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#460 🐛 Uplift containerd to v1.5.9
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#462 🐛 Uplift containerd to v1.5.9 and docker to v20.10.11
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#454 🌱 Don't set error on m3machine when it is not a terminal problem
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
Labels: size/S, approved, lgtm

#467 :seedling: Replace ironic image tag with main
  examples/addons.yaml
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#472 🌱 Move maelk to emeritus_approvers list
  OWNERS
Labels: size/XS, approved, lgtm

#473 🐛 Fix compilation issues in e2e tests
  test/e2e/common.go
  test/e2e/node_reuse_test.go
  test/e2e/remediation_test.go
Labels: size/S, approved, lgtm

#464 ✨ e2e: prepare for the new ironic container
  test/e2e/upgrade_ironic_test.go
Labels: size/XS, approved, lgtm

#451 ✨ Pin calico version to v3.21.0
  hack/e2e/environment.sh
  test/e2e/e2e_suite_test.go
Labels: size/S, approved, lgtm

#479 🌱 Remove static calico files from E2E tests in release-0.5 branch
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/cni/calico/calico-centos.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: size/XXL, approved, lgtm

#484 ✨ Pin calico version to v3.21.0 in release-0.5 branch
  hack/e2e/environment.sh
  test/e2e/e2e_suite_test.go
Labels: size/S, approved, lgtm

#483 ✨ Add re-inspection API tests to E2E
  test/e2e/config/e2e_conf.yaml
  test/e2e/inspection_test.go
  test/e2e/node_reuse_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#485 ✨ Add re-inspection API tests to E2E in release-0.5 branch
  test/e2e/config/e2e_conf.yaml
  test/e2e/inspection_test.go
  test/e2e/node_reuse_test.go
  test/e2e/remediation_test.go
Labels: approved, lgtm, size/L

#455 🐛 Rewrite MachineDeployment/MachineSet tests in m3machinemanager
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#463 ⚠️ Rename HasPausedAnnotation function to HasPaused
  controllers/metal3machinetemplate_controller.go
Labels: size/XS, approved, lgtm

#496 🌱 Uplift k8s to 1.23.3 and tilt settings to use CAPI v1.1.0-rc.0 release
  docs/api.md
  docs/dev-setup.md
  examples/generate.sh
  hack/fetch_ext_bins.sh
  hack/gen_tilt_settings.sh
Labels: approved, lgtm, size/M

#493 Replace ironic containers by the all-in-one
  test/e2e/pivoting_test.go
Labels: size/XS, approved, lgtm
