Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-06, with the labels that each got.

#998 :bug: Fix crio - calico CNI config collision on centos during e2e tests
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
Labels: size/XS, approved, lgtm

#1013 🐛 Fix race condition when associating BMH to M3M
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#1017 🌱 add features label for e2e feature tests for ginkgo focus
  test/e2e/live_iso_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
Labels: size/XS, approved, lgtm

#994 🌱 Bump Calico to v3.25.1
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#963 🌱 Seperate k8s and clusterctl upgrade tests
  scripts/environment.sh
  test/e2e/upgrade_kubernetes_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/S, approved, lgtm

#1009 :bug: Refactor taint usage and flow controll in node_reuse e2e test
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
Labels: approved, lgtm, size/L

#1020 🌱 update kubeconform to v0.6.2
  hack/manifestlint.sh
Labels: size/XS, approved, lgtm

#1022 🌱 Add lentzi90 as an approver
  OWNERS
Labels: size/XS, approved, lgtm

#1003 🌱 Add UT to HasFinalizer
  baremetal/metal3remediation_manager_test.go
Labels: size/XS, approved, lgtm

#950 :seedling: Added pod security standards manifest file for CAPM3
  Tiltfile
  config/default/capm3/namespace.yaml
Labels: size/XS, approved, lgtm

#1026 :bug: Increase machine deletion timeout during e2e tests
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1029 📖 Add Sunnat as a reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#1027 🌱 Add dependabot config and workflow
  .github/dependabot.yml
  .github/workflows/dependabot.yml
Labels: approved, lgtm, size/M

#1040 :bug: backport "wait for ironic/bmo deployment becomes available"
  test/e2e/pivoting.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#1042 🌱 fix distroless:nonroot pinning
  Dockerfile
Labels: size/XS, approved, lgtm

#1045 🌱 Include all gomods in different directories for Dependabot
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#1058 :bug: Removed mariadb restart check in certRotation test
  test/e2e/cert_rotation_test.go
Labels: size/XS, approved, lgtm

#1062 backport "Refactor taint usage and flow controll in node_reuse e2e test"
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
Labels: approved, lgtm, size/L

#1041 :sparkles: Add TLS configuration flags for CAPM3
  main.go
  main_test.go
Labels: approved, lgtm, size/L

#1063 :sparkles: Added tls configuration flags for CAPM3.
  main.go
  main_test.go
Labels: approved, lgtm, size/L

#1064 🌱 ignore ipam in dependabot config
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#1065 🌱 bump IPAM to 1.4.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1011 🐛 remove ipam pool reference defaulting to metal3
  api/v1beta1/metal3datatemplate_webhook.go
Labels: approved, lgtm, size/M

#1068 🐛 Fix k8s version based on clusterctl upgrade version
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_management_cluster_test.go
Labels: size/S, approved, lgtm

#1028 :sparkles: Bump golang to v1.20 and golangci-lint to v1.52.1
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  api/go.mod
  api/v1beta1/metal3cluster_webhook.go
  api/v1beta1/metal3machine_webhook.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  api/v1beta1/metal3remediation_webhook.go
  api/v1beta1/metal3remediationtemplate_webhook.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3data_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/suite_test.go
  controllers/metal3remediation_controller.go
  controllers/suite_test.go
  go.mod
  hack/build.sh
  hack/codegen.sh
  hack/ensure-golangci-lint.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/unit.sh
  test/e2e/common.go
  test/e2e/remediation.go
  test/go.mod
Labels: size/XL, approved, lgtm

#996 :book: remove .mdlrc and fix complaints
  .mdlrc
  CONTRIBUTING.md
  README.md
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  docs/disk_cleaning.md
  docs/e2e-test.md
  docs/getting-started.md
  docs/ip_reuse.md
  docs/remediation-controller.md
  hack/markdownlint.sh
  test/README.md
Labels: size/XXL, approved, lgtm

#1070 :bug: Disable TLS 1.0 and TLS 1.1
  main.go
Labels: size/S, approved, lgtm

#1072 🌱 Rename upgrade managment test and remove unecessary passed msg
  test/e2e/upgrade_clusterctl_test.go
Labels: size/XS, approved, lgtm

#1073 🐛 Set M3M concurrency to 1 and add warning
  main.go
Labels: size/XS, approved, lgtm
