Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-08, with the labels that each got.

#1113 Bump k8s version to v1.27.4
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  docs/e2e-test.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/L

#1118 🌱 Add the ssh log collection to logcollector
  test/e2e/common.go
  test/go.mod
Labels: approved, lgtm, size/L

#1122 🌱 Fix pivoting feature tests in release 1.3
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1124 🌱Add log and manifest collection for clusterctl upgrade test
  scripts/fetch_target_logs.sh
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#1129 🌱 Remove golangci-lint from hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/XL, approved, lgtm

#1125 :seedling: Fix code quality issues in TLS configuration code
  main.go
Labels: size/S, approved, lgtm

#1131 :seedling: bump x/net to 0.14.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1130 :seedling: bump x/net to 0.14.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1132 Point m3 dev env branch back to main
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#1133 🌱 bump IPAM to 1.3.3
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1140 🌱 Bump CAPI to v1.3.10
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/e2e/pivoting.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1142 🌱 bump IPAM to 1.4.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1141 🌱 Remove unnecessary replace blocks from go modules and update release document
  api/go.mod
  docs/releasing.md
  go.mod
  test/go.mod
Labels: size/S, approved, lgtm

#1137 🌱 Bump golangci-lint to v1.54.2
  .github/workflows/golangci-lint.yml
  hack/ensure-golangci-lint.sh
Labels: size/XS, approved, lgtm

#1145 🌱 Bump controller-tools to v0.12.1 and controller-runtime to v0.15.2
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1144 🌱 Bump k8s version to v1.28.1
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  docs/e2e-test.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/M

#1151 🌱 Add dependabot groups and allow patch updates
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#1155 🌱 bump golang build_image to 1.20.7
  Dockerfile
Labels: size/XS, approved, lgtm

#1158 🌱 Bump cert-manager to v1.12.3
  Tiltfile
  examples/generate.sh
  hack/gen_tilt_settings.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1156 🌱 Bump CAPI to v1.5.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1157 🌱 Bump CAPI to v1.4.6
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1159 🌱 Bump cert-manager to v1.12.3
  Tiltfile
  examples/generate.sh
  hack/gen_tilt_settings.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1164 🌱 bump IPAM to v1.5.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1167 :book: update README.md on 1.5 release
  README.md
Labels: size/S, approved, lgtm

#1168 🐛 Add missing CAPI v1.5 contract in e2e config
  test/e2e/data/shared/main/metadata.yaml
Labels: size/XS, approved, lgtm

#1172 🐛 Add CAPI contract for e2e in release-1.5
  test/e2e/data/shared/main/metadata.yaml
Labels: size/XS, approved, lgtm
