Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-09, with the labels that each got.

#1173 fix setting CAPI_CONFIG_FOLDER variable
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#1166 :book: update README.md
  README.md
Labels: approved, lgtm, size/M

#1179 🌱 Bump kind and kustomize and update bmh CRD
  Makefile
  examples/metal3crds/metal3.io_baremetalhosts.yaml
  hack/ensure-kind.sh
  hack/ensure-kustomize.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/ci-e2e.sh
Labels: approved, lgtm, size/L

#1177 :book: improve release notes tool
  hack/tools/release/notes.go
Labels: size/S, approved, lgtm

#1185 📖 fix typo in release note generator
  hack/tools/release/notes.go
Labels: size/XS, approved, lgtm

#1186 📖 improve release note generator
  hack/tools/release/notes.go
Labels: size/S, approved, lgtm

#1187 📖 improve release notes generator
  hack/tools/release/notes.go
Labels: size/S, approved, lgtm

#1191 🌱 add KUBECTL_SHA256 passthru
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#1188 🌱 add KUBECTL_SHA256 passthru
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/S, approved, lgtm

#1189 🌱 add KUBECTL_SHA256 passthru
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#1190 🌱 Remove unused and unmaintained phonys from Makefile
  Makefile
Labels: approved, lgtm, size/M

#1193 🌱 Fix v1.5 clusterctl upgrade tests
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#1195 📖 update releasing.md
  docs/releasing.md
Labels: approved, lgtm, size/M

#1196 🌱 Minor cleanups and added tests
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  main.go
Labels: approved, lgtm, size/L

#1209 🌱 run dependabot less often for GH actions
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#1214 🐛 fix ensure-golangci-lint digest for linux/amd64
  hack/ensure-golangci-lint.sh
Labels: size/S, approved, lgtm

#1213 🌱 bump gosec to 2.17.0, and fix gosec for submodules
  .golangci.yaml
  hack/gosec.sh
  test/e2e/common.go
  test/e2e/pivoting.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#1215 🌱 remove hack/gosec.sh
  hack/gosec.sh
Labels: size/S, approved, lgtm

#1218 🌱 bump gosec to 2.17.0, and fix gosec for submodules
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  hack/ensure-golangci-lint.sh
  hack/gosec.sh
  test/e2e/common.go
  test/e2e/pivoting.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#1139 :seedling: CRD labeling is done now by k8s api to fix gosec issues
  api/go.mod
  api/go.sum
  test/e2e/common.go
  test/e2e/pivoting.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1219 :bug: fix too tight file permissions in e2e
  test/e2e/common.go
Labels: size/XS, approved, lgtm

#1222 📖 fix releasing.md on annotated tags
  docs/releasing.md
Labels: size/XS, approved, lgtm

#1223 🌱 Uplift ipam to v1.3.4
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1225 🌱 Bumping CAPI to 1.5.2
  Dockerfile
  Makefile
  README.md
  Tiltfile
  api/go.mod
  api/go.sum
  examples/generate.sh
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1226 🌱 Bumping CAPI to 1.4.7
  Dockerfile
  README.md
  Tiltfile
  api/go.mod
  api/go.sum
  examples/generate.sh
  go.mod
  hack/gen_tilt_settings.sh
  test/e2e/config/e2e_conf.yaml
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1229 🌱Uplift ipam to v1.4.3
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1230 🌱Uplift IPAM to v1.5.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1231 📖 update contributing.md
  CONTRIBUTING.md
Labels: size/S, approved, lgtm

#1232 🌱 Bump capi/test module to v1.5.2
  test/go.mod
  test/go.sum
Labels: size/XS, approved, lgtm

#1233 🌱 Bump capi/test module to v1.4.7
  go.mod
  go.sum
  test/go.mod
Labels: size/S, approved, lgtm

#1228 :book: clarify tag usage in releasing.md
  docs/releasing.md
Labels: size/S, approved, lgtm
