Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-11, with the labels that each got.

#1307 🌱 Adding PR title verifier
  .github/workflows/pr-verifier.yaml
  .gitignore
Labels: size/S, approved, lgtm

#1309 📖 Commit signing off update.
  CONTRIBUTING.md
Labels: size/S, approved, lgtm

#1308 🌱 Remove duplicate healthcheck test trigger file
  test/e2e/healthcheck_test.go
Labels: approved, lgtm, size/M

#1330 🌱 improve hack/verify-release.sh draft release note handling
  hack/verify-release.sh
Labels: size/S, approved, lgtm

#1336 🌱Bump golang version 1.20.11 release-1.5
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1337 🌱Bump golang version to 1.20.11 for release-1.4
  Dockerfile
Labels: size/XS, approved, lgtm

#1335 🌱Bump golang version to 1.20.11
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1340 🌱Uplift IPAM and BMO patch in release-1.5
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1339 🌱Uplift IPAM v1.5.2 and BMO v0.4.1 patch release
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1342 🌱Uplift IPAM patch release tag v1.4.4 in CAPM3 release 1.4
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L
