Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-10, with the labels that each got.

#1237 🌱 fix typo in release note generator
  hack/tools/release/notes.go
Labels: size/XS, approved, lgtm

#1224 :book: Added prior art links to release documentation.
  docs/releasing.md
Labels: size/XS, approved, lgtm

#1243 🌱 bump IPAM to 1.5.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1238 :seedling: add hack/verify-release.sh script
  docs/releasing.md
  hack/verify-release.sh
Labels: size/XL, approved, lgtm

#1244 🌱 add hack/verify-release.sh
  hack/verify-release.sh
Labels: size/XL, approved, lgtm

#1245 🌱 add hack/verify-release.sh
  hack/verify-release.sh
Labels: size/XL, approved, lgtm

#1246 🌱 fix module printout in hack/verify-release.sh
  hack/verify-release.sh
Labels: size/XS, approved, lgtm

#708 ✨ Add bond hash policy
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1beta1/metal3datatemplate_types.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: ok-to-test, approved, lgtm, size/L

#1251 🐛 Fix IP-reuse deletion bug
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/L

#1256 🐛 IP reuse: Fix M3d/IPClaim deletion bug
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/L

#1255 🐛 IP reuse: Fix M3d/IPClaim deletion bug
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/L

#1252 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh
  hack/verify-release.sh
Labels: size/S, approved, lgtm

#1253 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh
  hack/verify-release.sh
Labels: size/S, approved, lgtm

#1254 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh
  hack/verify-release.sh
Labels: size/S, approved, lgtm

#1249 🐛 Fix one BMH associating to multiple M3Ms
  main.go
Labels: size/S, approved, lgtm

#1270 🌱 bump x/net to 0.17.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1269 🌱 bump x/net to 0.17.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1261 :seedling: Configurable go executable
  Makefile
Labels: ok-to-test, approved, lgtm, size/M

#1271 🌱 Bump golang to v1.20.10 and related change
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1272 🌱 Bump golang to v1.20.10 on release-1.5
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1273 🌱 Bump golang version to v1.20.10 on release-1.4
  .golangci.yaml
  Dockerfile
Labels: size/XS, approved, lgtm

#1268 :bug: Fix the "Could not find node with label" error message
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#1262 :sparkles: Enable mac address retrieved from annotations
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1beta1/metal3datatemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  docs/api.md
Labels: ok-to-test, approved, lgtm, size/L

#1292 🌱 bump k8s deps to v0.27.7
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1289 🌱 Minor code improvement in ensure-go
  hack/ensure-go.sh
Labels: size/XS, approved, lgtm

#1293 🌱 Bump CAPI to v1.5.3
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1294 🌱 Bump CAPI to v1.5.3
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1295 🌱 Bump CAPI to v1.4.8
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1296 🌱 bump onsi/gomega v1.29.0
  api/go.mod
  api/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, approved, lgtm

#1304 🌱 bump docker/docker to v24.0.7+incompatible
  test/go.mod
  test/go.sum
Labels: size/XS, approved, lgtm

#1303 🌱 bump docker/docker to v24.0.7+incompatible
  test/go.mod
  test/go.sum
Labels: size/XS, approved, lgtm
