Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-07, with the labels that each got.

#838 🌱 Remove and reinstall BMO in source cluster before and after pivot
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#1081 ✨ Add test failing and flaking issue templates
  .github/ISSUE_TEMPLATE/failing-test.yaml
  .github/ISSUE_TEMPLATE/flaking-test.yaml
Labels: approved, lgtm, size/M

#1087 🐛 Fix flaking test template
  .github/ISSUE_TEMPLATE/flaking-test.yaml
Labels: size/XS, approved, lgtm

#1092 🐛Enable Mariadb instead of SQLite
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1093 🐛Manual back port enabling mariadb instead of SQLite for release-1.4
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1089 ✨Introduce ReconcileError with Transient and Terminal Error type
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/reconcile_error.go
  baremetal/reconcile_error_test.go
  baremetal/requeue_error.go
  baremetal/requeue_error_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: size/XL, approved, lgtm

#1078 Add features label for e2e feature tests for ginkgo focus to release 1.4
  scripts/environment.sh
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/md.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
  test/e2e/upgrade_kubernetes_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: size/S, approved, lgtm

#1097 Revert "🐛Enable Mariadb instead of SQLite"
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1098 Revert "🐛Manual back port enabling mariadb instead of SQLite for release-1.4"
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#1086 ✨ Added a log collector implementation for Metal3
  test/e2e/common.go
  test/e2e/e2e_suite_test.go
  test/e2e/integration_test.go
Labels: approved, lgtm, size/L

#1088 Manual Backport of Kubernetes upgrade test related changes to release-1.3
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_kubernetes_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#1108 🌱 Update Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, approved, lgtm

#1101 🌱 Added basic integration test
  scripts/environment.sh
  test/e2e/basic_integration_test.go
Labels: approved, lgtm, size/M

#848 🌱 Add high level description to e2e tests
  test/e2e/inspection.go
  test/e2e/integration_test.go
  test/e2e/live_iso_test.go
  test/e2e/metal3remediation.go
  test/e2e/node_reuse.go
  test/e2e/pivoting.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_baremetal_operator.go
  test/e2e/upgrade_ironic.go
  test/e2e/upgrade_kubernetes_test.go
Labels: approved, lgtm, size/L

#1112 🌱 Add basic tests to the Readme
  README.md
Labels: size/S, approved, lgtm
