Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-04, with the labels that each got.

#918 🌱 Disable scheduled workflows from running in forks
  .github/workflows/kubesec.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/release.yaml
Labels: size/XS, approved, lgtm

#917 🌱 cleanup hack/ formatting
  hack/build.sh
  hack/codegen.sh
  hack/ensure-go.sh
  hack/ensure-golangci-lint.sh
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/ensure-kustomize.sh
  hack/gen_tilt_settings.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/gosec.sh
  hack/govet.sh
  hack/kind_with_registry.sh
  hack/kustomize-sub.sh
  hack/manifestlint.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
  hack/unit.sh
  hack/verify-boilerplate.sh
Labels: size/XL, approved, lgtm

#923 🐛 fix malformatted pipefail option in ci-e2e.sh
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#922 🌱 Improve target log collection for e2e
  scripts/fetch_target_logs.sh
  test/e2e/integration_test.go
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#924 🌱Refactor target log collection script
  scripts/fetch_target_logs.sh
  test/e2e/pivoting.go
Labels: size/S, approved, lgtm

#925 🌱Add manifest collection for e2e test
  scripts/fetch_manifests.sh
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#927 🌱Add manifest collection after re-pivot
  scripts/fetch_manifests.sh
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#929 🌱Uplift IPAM release-1.2 tag v1.2.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#930 🌱 bump IPAM to 1.3.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#932 🌱 Bump cert-manager to v1.11.1
  Tiltfile
  examples/generate.sh
  hack/gen_tilt_settings.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/XS, approved, lgtm

#935 🌱 bump IPAM to 1.4.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#916 📖 update releasing.md
  docs/releasing.md
  hack/tools/release/notes.go
Labels: approved, lgtm, size/L

#938 📖 update releasing.md and fix typos
  docs/releasing.md
Labels: approved, lgtm, size/M

#937 🌱 bump BMO to 0.3.0-rc.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#769 ✨ implement CAPI IPAM contract support
  api/v1alpha5/conversion.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1beta1/metal3datatemplate_types.go
  api/v1beta1/metal3datatemplate_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/suite_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/rbac/role.yaml
  controllers/metal3datatemplate_controller.go
  main.go
Labels: size/XXL, approved, lgtm

#939 🌱 bump BMO to 0.3.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#943 🌱 Add Rozzii as reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#944 🌱 Add release-1.4 related changes
  Makefile
  README.md
Labels: size/S, approved, lgtm

#953 🌱 update build badges to point to 1.2
  README.md
Labels: size/S, approved, lgtm
