Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-12, with the labels that each got.

#1353 🐛 Use pflag instead of go flag for TLSMinVersion
  main.go
Labels: size/XS, approved, lgtm

#1311 ✨ Don't assume KubeadmControlPlane for nodeReuse
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  docs/api.md
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/L

#1359 🌱 add clomonitor badge to README
  README.md
Labels: size/XS, approved, lgtm

#1361 🐛 Fix race condition getting IPAddress for Metal3Data
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/M

#1367 🌱 bump x/crypto to 0.17.0
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1366 🌱 bump x/crypto to 0.17.0
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1362 ⚠️ Stop serving v1alpha5 API Versions
  api/v1alpha5/metal3cluster_types.go
  api/v1alpha5/metal3data_types.go
  api/v1alpha5/metal3dataclaim_types.go
  api/v1alpha5/metal3datatemplate_types.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/metal3machine_types_test.go
  api/v1alpha5/metal3machinetemplate_types.go
  api/v1alpha5/metal3remediation_types.go
  api/v1alpha5/metal3remediationtemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
Labels: approved, lgtm, size/M

#1369 🌱 add OpenSSF Scorecard badge to README
  README.md
Labels: size/XS, approved, lgtm

#1360 🌱 Use k8s apimachinery scheme builder instead of controller-runtime scheme builder
  api/v1beta1/groupversion_info.go
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3data_types.go
  api/v1beta1/metal3dataclaim_types.go
  api/v1beta1/metal3datatemplate_types.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machinetemplate_types.go
  api/v1beta1/metal3remediation_types.go
  api/v1beta1/metal3remediationtemplate_types.go
  api/v1beta1/v1beta1_suite_test.go
Labels: approved, lgtm, size/M
