Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-03, with the labels that each got.

#872 Revert "🐛 Remove bmhID arg from SetNodeProviderID call"
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/M

#873 :bug: Fix Makefile command chaining
  Makefile
Labels: approved, lgtm, size/M

#878 🌱 Bump CAPI to v1.2.11
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#880 🐛 Fix Makefile command chaining
  Makefile
  hack/build.sh
  hack/gofmt.sh
  test/e2e/e2e_suite_test.go
  test/e2e/live_iso_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#883 📖 Unify e2e triggers format
  README.md
Labels: approved, lgtm, size/M

#884 ✨Enable concurrency in metal3 controllers
  controllers/metal3cluster_controller.go
  controllers/metal3data_controller.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3labelsync_controller.go
  controllers/metal3machine_controller.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3remediation_controller.go
  main.go
Labels: approved, lgtm, size/L

#836 🌱 Add m3d waiting condition to m3m object
  api/v1beta1/condition_consts.go
  baremetal/metal3data_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3machine_controller.go
Labels: approved, lgtm, size/M

#877 🐛Remove bmhID arg from SetNodeProviderID call
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#849 🌱 Add new condition reasons to m3machine
  api/v1beta1/condition_consts.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/L

#885 :seedling: Add support for new dev-env network variable names in e2e tests
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/ippool/ippool.yaml
  test/e2e/pivoting.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#888 ⚠️ Bump CAPI to v1.4.0-rc.0
  .golangci.yaml
  README.md
  api/go.mod
  api/go.sum
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  clusterctl-settings.json
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  controllers/metal3cluster_controller.go
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3labelsync_controller.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  metadata.yaml
  test/e2e/data/infrastructure-metal3/v1beta1/metadata.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/live_iso_test.go
  test/go.mod
  test/go.sum
Labels: size/XXL, approved, lgtm

#891 Changing MACAddressPolicy to none
  scripts/environment.sh
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Labels: size/XS, approved, lgtm

#895 🐛 manifestlint: move from kubeval to kubeconform
  hack/manifestlint.sh
Labels: approved, lgtm, size/M

#899 🌱 sync OWNERS from main
  OWNERS
Labels: size/S, approved, lgtm

#900 🌱 sync OWNERS from main
  OWNERS
Labels: size/S, approved, lgtm

#892 🌱 Bump CAPI to v1.4.0-rc.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#902 🐛 cherry-pick gomod.sh changes from main
  hack/gomod.sh
Labels: approved, lgtm, size/M

#903 🐛 Bump go modules for getting rid of CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XL, approved, lgtm

#906 :bug: Fix typo in e2e environment config
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#912 :seedling: Backport support for dev-env new network variable names in e2e tests (release-1.3)
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/ippool/ippool.yaml
  test/e2e/pivoting.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#913 :seedling: Backport support for dev-env new network variable names in e2e tests (release-1.2)
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/ippool/ippool.yaml
Labels: size/S, approved, lgtm

#914 :seedling: Backport support for dev-env new network variable names in e2e tests (release-1.1)
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/ippool/ippool.yaml
Labels: size/S, approved, lgtm
