Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-01, with the labels that each got.

#823 🌱 Bump k8s to v1.26.0
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Labels: approved, lgtm, size/M

#751 🌱 Add kubernetes upgrade test to e2e upgrade
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
  test/e2e/upgrade_kubernetes_test.go
Labels: approved, lgtm, size/L

#824 🌱 manifestlint: move from kubeval to kubeconform
  hack/manifestlint.sh
Labels: approved, lgtm, size/M

#798 🌱 Add integration test to e2e
  Makefile
  scripts/environment.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/integration.go
  test/e2e/integration_test.go
  test/e2e/pivoting.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: size/XL, approved, lgtm

#825 🐛 .github: secure github actions
  .github/workflows/kubesec.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/M

#833 🌱 pin golang to 1.19.4 with digest
  Dockerfile
Labels: size/XS, approved, lgtm

#834 🌱 use docker.io consistently, and pin more checks
  hack/gomod.sh
  hack/gosec.sh
  hack/markdownlint.sh
Labels: size/XS, approved, lgtm

#829 🌱 Uplift CAPI to v1.3.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#832 🌱 Uplift capi to v1.2.9
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#828 🌱 Uplift CAPI to v1.3.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#822 ✨ add explicit securitycontext to controllers
  Tiltfile
  config/manager/manager.yaml
  hack/tools/remove_sec_ctx.py
Labels: approved, lgtm, size/L

#805 🐛 Use gingko cli and timeout
  Makefile
Labels: approved, lgtm, size/M

#837 :bug: Clean varenv after mngmt upgrade
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_management_cluster_test.go
Labels: size/S, approved, lgtm

#840 🌱 hack: update ensure-kind.sh
  hack/ensure-kind.sh
Labels: size/S, approved, lgtm

#843 🌱 Add tuminoid as a reviewer
  OWNERS
Labels: size/XS, approved, lgtm

#842 🌱 kubesec: update codeql-action to v2
  .github/workflows/kubesec.yml
Labels: size/XS, approved, lgtm

#816 🌱 E2e: Support running Ironic with MariaDB
  test/e2e/cert_rotation.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/pivoting.go
  test/e2e/upgrade_ironic.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M
