Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-02, with the labels that each got.

#826 🌱 Add inegration test trigger to the README
  README.md
Labels: size/S, approved, lgtm

#845 🌱Add trigger phrases in the doc to keep VM for e2e CI jobs
  README.md
Labels: size/S, approved, lgtm

#846 🌱 Bump CAPI to v1.3.3
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#853 🐛 bump kustomize to 4.5.7
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#851 🌱 Bump Dockerfile golang image tag to v1.19.5
  Dockerfile
Labels: size/XS, approved, lgtm

#855 🌱 Bump Dockerfile golang image tag to v1.19.5
  Dockerfile
Labels: size/XS, approved, lgtm

#856 📖Update README file to add keep VM trigger
  README.md
Labels: size/XS, approved, lgtm

#857 :bug: hack: gomod needs to verify all go.mod files
  hack/gomod.sh
Labels: approved, lgtm, size/M

#854 🌱 Bump Dockerfile golang image tag to v1.18.10
  Dockerfile
Labels: size/XS, approved, lgtm

#861 🐛 hack: gomod needs to verify all go.mod files
  hack/gomod.sh
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#862 hack: gomod needs to verify all go.mod files
  hack/gomod.sh
Labels: approved, lgtm, size/M

#860 🌱 Add mboukhalfa as an approver
  OWNERS
Labels: size/S, approved, lgtm

#852 🌱 Bump CAPI to v1.2.10
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#864 🐛 uplift golang and x/net
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#868 🐛 Remove bmhID arg from SetNodeProviderID call
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/mocks/zz_generated.metal3machine_manager.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: approved, lgtm, size/M
