Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2023-05, with the labels that each got.

#942 🌱 Backport e2e log improvements to release-1.3
  scripts/fetch_target_logs.sh
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#959 ✨ Add flags for configuring rate limits
  .gitignore
  main.go
Labels: size/S, approved, lgtm

#956 🐛 Point build status to e2e instead of ansible
  README.md
Labels: size/XS, approved, lgtm

#960 🐛 Fix kubernetes version for e2e tests
  docs/e2e-test.md
  scripts/ci-e2e.sh
Labels: size/S, approved, lgtm

#961 🌱 Bump CAPI to v1.4.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#965 🌱Backport manifest collection
  scripts/fetch_manifests.sh
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#936 🌱 Add wait for ironic/bmo deployment becomes available
  test/e2e/pivoting.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#870 🌱 Improve logging around ProviderID and BMHID formulation
  baremetal/metal3machine_manager.go
  controllers/metal3machine_controller.go
Labels: size/XS, approved, lgtm

#955 📖 update releasing.md with post-release actions
  docs/releasing.md
Labels: approved, lgtm, size/M

#966 🌱 Bump k8s to v1.27.1
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  docs/e2e-test.md
  examples/generate.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/md.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/ubuntu-kubeadm-config.yaml
Labels: approved, lgtm, size/M

#967 🐛 Deploy ironic before bmo in upgrade test
  test/e2e/upgrade_management_cluster_test.go
Labels: size/S, approved, lgtm

#969 :seedling: uplift golang image from 1.19.6 to 1.19.9
  Dockerfile
Labels: size/XS, approved, lgtm

#970 🌱 bump golang image from 1.19.6 to 1.19.9, pin distroless
  Dockerfile
Labels: size/XS, approved, lgtm

#978 🌱 Bump controller-tools to v0.11.4
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#976 :bug: tools: add setup-envtest to tools.go
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/S, approved, lgtm

#977 :bug: Remove kubeconfig from .gitignore
  .gitignore
Labels: size/XS, approved, lgtm

#972 📖 Add support and guarantees section in Contributing guide
  CONTRIBUTING.md
Labels: approved, lgtm, size/M

#934 🐛 Fix cleanup for keep tests
  Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/live_iso_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_kubernetes_test.go
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/M

#987 :seedling: Changing md5 to sha256 in tests and default tempelates
  api/v1alpha5/common_types.go
  api/v1alpha5/metal3machine_types_test.go
  api/v1beta1/common_types.go
  api/v1beta1/common_types_test.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3machine_controller_integration_test.go
  docs/api.md
  docs/architecture.md
  docs/getting-started.md
  examples/clusterctl-templates/example_variables.rc
  examples/generate.sh
  examples/metal3plane/hosts.yaml
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
Labels: approved, lgtm, size/L

#988 :seedling: Changing md5 to sha256 in tests and default tempelates
  api/v1alpha5/common_types.go
  api/v1alpha5/metal3machine_types_test.go
  api/v1beta1/common_types.go
  api/v1beta1/common_types_test.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3machine_controller_integration_test.go
  docs/api.md
  docs/architecture.md
  docs/getting-started.md
  examples/clusterctl-templates/example_variables.rc
  examples/generate.sh
  examples/metal3plane/hosts.yaml
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse_test.go
Labels: approved, lgtm, size/L

#990 :bug: Fixing sha256sum generation
  test/e2e/common.go
Labels: size/XS, approved, lgtm

#984 :seedling: Changing md5 to sha256 in tests and default tempelates
  api/v1alpha5/common_types.go
  api/v1alpha5/metal3machine_types_test.go
  api/v1beta1/common_types.go
  api/v1beta1/common_types_test.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  controllers/metal3machine_controller_integration_test.go
  docs/api.md
  docs/architecture.md
  docs/getting-started.md
  examples/clusterctl-templates/example_variables.rc
  examples/generate.sh
  examples/metal3plane/hosts.yaml
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
  test/e2e/upgrade_kubernetes_test.go
Labels: approved, lgtm, size/L

#992 :bug: Fixing sha256sum generation
  test/e2e/common.go
  test/e2e/node_reuse_test.go
Labels: size/S, approved, lgtm

#983 🌱 Bump github.com/docker/distribution to v2.8.2
  api/go.mod
  go.mod
  go.sum
Labels: size/S, approved, lgtm

#993 :bug: Modify kubeadm scripts to re-enable IPAM integration in e2e tests
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/L

#995 🌱 Remove CAPM3 release-1.1 from README
  README.md
Labels: size/XS, approved, lgtm

#904 🌱 Add release 1.1 upgrade test
  README.md
  clusterctl-settings.json
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/main/metadata.yaml
  test/e2e/data/infrastructure-metal3/v0.5/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1.1/metadata.yaml
  test/e2e/data/shared/main/metadata.yaml
  test/e2e/data/shared/v0.4/metadata.yaml
  test/e2e/data/shared/v1.1/metadata.yaml
  test/e2e/data/shared/v1.4/metadata.yaml
  test/e2e/upgrade_management_cluster_test.go
Labels: approved, lgtm, size/L

#910 ✨Introduce ReconcileError with Transient and Terminal Error type
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/reconcile_error.go
  baremetal/reconcile_error_test.go
  baremetal/requeue_error.go
  baremetal/requeue_error_test.go
  baremetal/utils.go
  baremetal/utils_test.go
  controllers/metal3data_controller.go
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3datatemplate_controller_test.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
Labels: size/XL, approved, lgtm

#999 🌱 Uplift ipam to v1.3.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1001 🌱 backport mariadb-image line to release note generator
  hack/tools/release/notes.go
Labels: size/XS, approved, lgtm

#1005 🌱 Make container registry for e2e calico manifest configurable
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
Labels: size/XS, approved, lgtm
