Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-07, with the labels that each got.

#1821 🌱 schedule dependabot on certain day, and add ok-to-test automatically
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#1822 :seedling: remove KUBECTL_SHA256 passthru
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#1826 🌱 remove KUBECTL_SHA256 passthru
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#1827 🌱 remove KUBECTL_SHA256 passthru
  scripts/ci-e2e.sh
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#1830 🌱 bump golang to 1.22.5
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1596 🐛 Fixing bmo version for clusterctl tests
  scripts/ci-e2e.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/bmo-deployment/components/basic-auth/credentials_patch.yaml
  test/e2e/data/bmo-deployment/components/basic-auth/kustomization.yaml
  test/e2e/data/bmo-deployment/components/tls/kustomization.yaml
  test/e2e/data/bmo-deployment/components/tls/tls_ca_patch.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.4/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.4/kustomization.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.5/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.5/kustomization.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.6/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.6/kustomization.yaml
  test/e2e/data/bmo-deployment/overlays/release-latest/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-latest/kustomization.yaml
  test/e2e/data/ironic-deployment/components/basic-auth/auth.yaml
  test/e2e/data/ironic-deployment/components/basic-auth/ironic-auth-config-tpl
  test/e2e/data/ironic-deployment/components/basic-auth/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-23.1/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-23.1/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-23.1/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-24.0/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.0/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.1/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-24.1/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.1/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-latest/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-latest/kustomization.yaml
  test/e2e/upgrade_baremetal_operator.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_ironic.go
  test/go.mod
  test/go.sum
Labels: size/XXL, approved, lgtm

#1805 ✨ Bump CAPI to v1.8.0 pre alpha
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/XL, approved, lgtm

#1751 :warning: Fix enableBMHNameBasedPreallocation label to ENABLE_BMH_NAME_BASED_PR…
  config/manager/manager.yaml
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#1834 🌱 Bump CAPI to v1.6.7
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1833 🐛 Fixing bmo version for clusterctl tests
  scripts/ci-e2e.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/bmo-deployment/components/basic-auth/credentials_patch.yaml
  test/e2e/data/bmo-deployment/components/basic-auth/kustomization.yaml
  test/e2e/data/bmo-deployment/components/tls/kustomization.yaml
  test/e2e/data/bmo-deployment/components/tls/tls_ca_patch.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.4/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.4/kustomization.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.5/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.5/kustomization.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.6/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.6/kustomization.yaml
  test/e2e/data/ironic-deployment/components/basic-auth/auth.yaml
  test/e2e/data/ironic-deployment/components/basic-auth/ironic-auth-config-tpl
  test/e2e/data/ironic-deployment/components/basic-auth/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-23.1/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-23.1/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-23.1/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-24.0/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.0/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.1/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-24.1/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.1/kustomization.yaml
  test/e2e/upgrade_baremetal_operator.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_ironic.go
  test/go.mod
  test/go.sum
Labels: size/XXL, approved, lgtm

#1835 🌱 Bump CAPI to v1.7.4
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1842 :bug: Fixing bmo and ironic version for clusterctl tests
  scripts/ci-e2e.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/bmo-deployment/components/basic-auth/credentials_patch.yaml
  test/e2e/data/bmo-deployment/components/basic-auth/kustomization.yaml
  test/e2e/data/bmo-deployment/components/tls/kustomization.yaml
  test/e2e/data/bmo-deployment/components/tls/tls_ca_patch.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.5/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.5/kustomization.yaml
  test/e2e/data/ironic-deployment/components/basic-auth/auth.yaml
  test/e2e/data/ironic-deployment/components/basic-auth/ironic-auth-config-tpl
  test/e2e/data/ironic-deployment/components/basic-auth/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-23.1/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-23.1/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-23.1/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-24.0/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-24.0/kustomization.yaml
  test/e2e/upgrade_baremetal_operator.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_ironic.go
  test/go.mod
  test/go.sum
Labels: size/XL, approved, lgtm

#1843 📖 Update triggers for feature tests
  README.md
Labels: approved, lgtm, size/M

#1852 🌱 Bump golang to v1.22
  Dockerfile
  Makefile
  Tiltfile
  api/go.mod
  go.mod
  go.sum
  hack/build.sh
  hack/codegen.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/unit.sh
  test/go.mod
Labels: approved, lgtm, size/M

#1808 ✨ Use Out-of-service taint in Node remediation in place of deletion
  baremetal/metal3remediation_manager.go
  baremetal/mocks/zz_generated.metal3remediation_manager.go
  config/rbac/role.yaml
  controllers/metal3remediation_controller.go
  controllers/metal3remediation_controller_test.go
  main.go
  test/e2e/common.go
  test/e2e/node_deletion_remediation.go
  test/e2e/remediation_based_feature_test.go
  test/go.mod
  test/go.sum
Labels: ok-to-test, size/XL, approved, lgtm
