Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-02, with the labels that each got.

#1445 🌱 Bump controller-runtime to v0.16.4
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1467 🌱 Bump CAPI to v1.6.2
  README.md
  api/go.mod
  api/go.sum
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  baremetal/metal3cluster_manager_test.go
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3machinetemplate_manager_test.go
  baremetal/utils_test.go
  controllers/metal3cluster_controller.go
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3machine_controller_test.go
  controllers/metal3machinetemplate_controller_test.go
  go.mod
  go.sum
  test/e2e/common.go
  test/e2e/inspection.go
  test/e2e/live_iso_test.go
  test/e2e/remediation.go
  test/e2e/upgrade_clusterctl_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1476 🌱 Bump golang to v1.21.7
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1477 🌱 Bump golang to v1.20.14
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1468 🌱 Bump CAPI to v1.5.6
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1475 🌱 Bump CAPI to v1.6.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/upgrade_clusterctl_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M
