Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-05, with the labels that each got.

#1608 📖 Add info about k8s-upgrade tests for release branches
  README.md
  docs/e2e-test.md
Labels: ok-to-test, approved, lgtm, size/M

#1634 :seedling: Release-1.7 related changes
  CONTRIBUTING.md
  Makefile
  README.md
  docs/e2e-test.md
  hack/verify-release.sh
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: ok-to-test, approved, lgtm, size/L

#1642 🌱 Add Slack notification for image build workflow failure
  .github/workflows/build-images-action.yml
Labels: size/S, approved, lgtm

#1653 🌱 Move furkatgofurov7 to emeritus approvers
  OWNERS
Labels: size/XS, approved, lgtm

#1652 🌱 set webhook min TLS version to 1.3
  main.go
Labels: size/XS, approved, lgtm

#1663 🌱 Add Adil, Moshiur, Sunnat and Tuomo as approvers and Dmitry as a reviewer
  OWNERS
Labels: approved, lgtm, size/M

#1667 :book: Fix dead link to ubuntu feature test
  README.md
Labels: size/XS, approved, lgtm

#1666 🌱 Bump CAPI v1.6.5
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1658 🌱 Fix log.SetLogger(...) was never called issue
  test/e2e/e2e_suite_test.go
  test/go.mod
Labels: size/XS, approved, lgtm

#1672 🌱 Configure dependabot for release-1.7 branch
  .github/dependabot.yml
Labels: approved, lgtm, size/L

#1708 🌱 Fix dependabot release branch config to bump only patch versions
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#1713 🌱 Group dependabot k8s bumps for release branches and ignore major, minor bumps for all dependancies
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#1718 🌱 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/M

#1719 🌱 Bump only patch versions for release branch github actions
  .github/dependabot.yml
Labels: ok-to-test, size/XS, approved, lgtm

#1665 🌱 Bump CAPI to v1.7.2
  README.md
  api/go.mod
  api/go.sum
  docs/e2e-test.md
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1671 :bug: Clusterclass e2e test fix
  Makefile
  examples/templates/clusterclass.yaml
Labels: ok-to-test, size/XS, approved, lgtm

#1724 🌱 refactor TLS config
  main.go
  main_test.go
Labels: approved, lgtm, size/M

#1727 🌱 Bump CAPI to v1.7.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1726 :seedling: Add unit tests for duplicateProviderIDsExist
  baremetal/metal3machine_manager_test.go
Labels: approved, lgtm, size/L

#1730 🌱 Minor cleaning of M3DT manager code
  baremetal/metal3datatemplate_manager.go
  controllers/metal3datatemplate_controller.go
Labels: approved, lgtm, size/M

#1732 🌱 Allow minor version bumps for golang.org/x/* dependancies for release branch
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#1741 🌱 remove kubesec workflow
  .github/workflows/kubesec.yml
Labels: approved, lgtm, size/M

#1501 ✨ Support CustomDeploy in addition to Image
  api/v1beta1/common_types.go
  api/v1beta1/metal3machine_types.go
  api/v1beta1/metal3machine_webhook.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
Labels: ok-to-test, approved, lgtm, size/L

#1731 :seedling: explicitly drop pr approver workflow permissions
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: size/XS, approved, lgtm

#1478 :bug: Protect Metal3Data and Metal3DataClaim with Finalizers
  baremetal/metal3data_manager.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  baremetal/metal3machine_manager.go
  baremetal/utils.go
  controllers/metal3data_controller.go
Labels: approved, lgtm, size/L

#1745 🌱 Move golang.org/x/* ignore rules after the * rule
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#1625 🌱 Update Kustomize deprecated syntax
  config/certmanager/certificate.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_metal3clusters.yaml
  config/crd/patches/cainjection_in_metal3dataclaims.yaml
  config/crd/patches/cainjection_in_metal3datas.yaml
  config/crd/patches/cainjection_in_metal3datatemplates.yaml
  config/crd/patches/cainjection_in_metal3machines.yaml
  config/crd/patches/cainjection_in_metal3machinetemplates.yaml
  config/crd/patches/cainjection_in_metal3remediations.yaml
  config/crd/patches/cainjection_in_metal3remediationtemplates.yaml
  config/default/capm3/kustomization.yaml
  config/default/capm3/manager_webhook_patch.yaml
  config/default/capm3/webhookcainjection_patch.yaml
  config/default/kustomization.yaml
  config/ipam/kustomization.yaml
  config/manager/kustomization.yaml
  config/webhook/kustomization.yaml
  examples/provider-components/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/ubuntu-kubeadm-config/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-ubuntu/kustomization.yaml
Labels: ok-to-test, approved, lgtm, size/L
