Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-01, with the labels that each got.

#1385 [release-1.5] 🐛 Fix race condition getting IPAddress for Metal3Data
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
Labels: approved, lgtm, size/M

#1392 🌱 bump golang to 1.20.12
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1394 🌱 bump golang to 1.20.12
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1338 🌱 Add github action to trigger container image build
  .github/workflows/build-images-action.yml
Labels: size/S, approved, lgtm

#1397 🌱 remove release-1.3
  README.md
  scripts/ci-e2e.sh
Labels: approved, lgtm, size/M

#1386 🌱 reduce github actions permissions
  .github/workflows/build-images-action.yml
  .github/workflows/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/kubesec.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-verifier.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/L

#1400 🐛 Fix for v1.6 clusterctl upgrade.
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#1399 🌱 Bump k8s to v1.29.0
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  docs/e2e-test.md
  examples/generate.sh
  hack/ensure-kubectl.sh
  hack/gen_tilt_settings.sh
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: approved, lgtm, size/L

#1403 🌱 bump ginkgo to v2.14.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1406 🌱 Bump CAPI to v1.6.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1407 🌱 Bump CAPI to v1.5.5
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1409 📖 Update Support matrix in Contributing guide
  CONTRIBUTING.md
Labels: size/XS, approved, lgtm

#1411 🌱 Bump envtest to v1.29.x
  Makefile
Labels: size/XS, approved, lgtm

#1412 🌱 Add ginkgo phony in Makefile
  Makefile
Labels: size/XS, approved, lgtm

#1415 🐛 Install ginkgo directly instead of building it using go-modules
  Makefile
Labels: size/S, approved, lgtm

#1430 🌱 bump k8s.io/* deps to v0.28.6
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1414 :book: switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  CONTRIBUTING.md
  docs/api.md
  hack/markdownlint.sh
Labels: approved, lgtm, size/M

#1432 🐛 Default k8s version in ensure-kubectl script
  hack/ensure-kubectl.sh
Labels: size/XS, approved, lgtm

#1433 🐛 Fix for kubectl version command for different versions of k8s
  hack/ensure-kubectl.sh
Labels: size/XS, approved, lgtm

#1435 🌱 Bump golang to v1.21.6
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  api/go.mod
  api/go.sum
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  go.mod
  go.sum
  hack/build.sh
  hack/codegen.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/unit.sh
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1436 🌱 Fix Permission Issue for process.txt in Tiltfile Configuration
  Tiltfile
Labels: size/XS, approved, lgtm
