Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-04, with the labels that each got.

#1465 🌱 Simplifying and updating clusterctl upgrade tests
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L

#1464 🌱 Fixing and simplifying clusterctl upgrade tests
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L

#1576 🌱 Add release markers to e2e config
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#1564 📖 Update e2e feature tests triggers
  README.md
Labels: approved, lgtm, size/M

#1581 🌱 Bump CAPI to v1.7.0-rc.0
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1583 🌱 add workflow to approve actions on PR change
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: approved, lgtm, size/M

#1585 🌱 Bump golang.org/x/net to v0.23.0 and golang to v1.21.9
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1592 🌱 Bump CAPI to v1.7.0-rc.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1575 🌱 Use PostNamespaceCreated hook to apply bmh in clusterctl upgrade
  scripts/environment.sh
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#1582 🌱 Update e2e integration triggers
  README.md
Labels: approved, lgtm, size/M

#1602 🌱 BUMP CAPI to v1.5.8
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1604 🌱 Bump CAPI to v1.7.0
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1603 🌱 Bump CAPI to v1.6.4
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1605 🌱 Uplift BMO to release-0.6 and IPAM to v1.7.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1512 🌱 Update e2e triggers for release-1.6
  README.md
Labels: approved, lgtm, size/L

#1598 🌱 [release-1.5] Update triggers after migration to prow
  README.md
Labels: approved, lgtm, size/M

#1618 🌱 Update README on job triggers in release-1.7
  README.md
Labels: ok-to-test, approved, lgtm, size/M

#1624 🌱 Remove keep test env related vars and configs
  Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/ip_reuse_test.go
  test/e2e/live_iso_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: ok-to-test, approved, lgtm, size/M

#1626 🌱 improve hack/verify-release.sh
  hack/verify-release.sh
Labels: ok-to-test, approved, lgtm, size/M

#1620 🌱 bump CAPI to v1.7.1
  CONTRIBUTING.md
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: ok-to-test, approved, lgtm, size/M

#1622 🌱 Bump k8s to v1.30.0
  Makefile
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  examples/generate.sh
  hack/ensure-kubectl.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: ok-to-test, approved, lgtm, size/M

#1623 🌱 Remove deprecated/unused vars from e2e config
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
Labels: ok-to-test, approved, lgtm, size/M

#1633 🌱 Bump Kubernetes upgrade from version
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#1405 :seedling: Support for ClusterClass template
  Makefile
  Tiltfile
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3clustertemplate_types.go
  api/v1beta1/metal3clustertemplate_webhook.go
  api/v1beta1/metal3clustertemplate_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clustertemplates.yaml
  config/crd/kustomization.yaml
  config/webhook/manifests.yaml
  examples/generate.sh
  examples/templates/cluster.yaml
  examples/templates/clusterclass.yaml
  hack/gen_tilt_settings.sh
  main.go
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-centos-kubeadm-config/clusterclass-centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-centos-kubeadm-config/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-cluster/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-cluster/crs.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-cluster/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-cluster/md.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-ubuntu-kubeadm-config/clusterclass-ubuntu-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-ubuntu-kubeadm-config/kustomization.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass/clusterclass.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-metal3/clusterclass-template-centos/kustomization.yaml
  test/e2e/data/infrastructure-metal3/clusterclass-template-ubuntu/kustomization.yaml
  test/e2e/data/infrastructure-metal3/clusterclass-template-upgrade-workload/kustomization.yaml
  test/e2e/data/infrastructure-metal3/clusterclass/kustomization.yaml
Labels: ok-to-test, size/XXL, approved, lgtm
