Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-09, with the labels that each got.

#1946 :seedling: Uplift BMO to v0.8.0 and IPAM to v1.8.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1944 :seedling: Uplift BMO to v0.8.0 and IPAM to v1.8.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1948 :seedling: Uplift BMO to v0.5.2
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1949 :seedling: Uplift BMO to v0.6.2
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1957 📖 Fix issues in test links and triggers
  README.md
Labels: size/S, approved, lgtm

#1956 :book: Update job triggers documents
  README.md
Labels: approved, lgtm, size/M

#1959 :seedling: Fix Centos e2e feature test badge
  README.md
Labels: size/XS, approved, lgtm

#1960 :seedling: Fix remediation test badge name
  README.md
Labels: size/XS, approved, lgtm

#1962 :seedling: Uplift CAPI in test/ to v1.6.8
  test/go.mod
  test/go.sum
Labels: size/XS, approved, lgtm

#1963 :seedling: Bump CAPI to v1.8.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1964 :seedling: Bump CAPI to v1.8.2
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1922 🐛 Fix cert rotation tests
  test/e2e/cert_rotation.go
Labels: approved, lgtm, size/M

#1974 🌱 Uplifts CAPI v1.7.6
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1973 🌱 Uplift CAPI to v1.8.3
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1911 🌱 Use CAPI's ClusterCacheTracker
  controllers/metal3cluster_controller.go
  controllers/metal3data_controller.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3labelsync_controller.go
  controllers/metal3machine_controller.go
  controllers/metal3machinetemplate_controller.go
  controllers/metal3remediation_controller.go
  main.go
Labels: approved, lgtm, size/M

#1995 🌱 Reuse PR verifier workflow from project-infra
  .github/workflows/pr-verifier.yaml
Labels: size/S, approved, lgtm
