Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-08, with the labels that each got.

#1859 🌱 Uplift CAPI to v1.8.0-rc.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  main.go
  main_test.go
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1858 🌱 Bump golang 1.22 in release 1.6
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  controllers/metal3data_controller_test.go
  controllers/metal3datatemplate_controller_test.go
  hack/build.sh
  hack/codegen.sh
  hack/ensure-go.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/M

#1873 🌱 bump k8s.io/* deps to v0.28.12
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1874 🌱 Uplift CAPI to v1.8.0-rc.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1883 🌱 Set terminationMessagePolicy to FallbackToLogsOnError for manager
  config/manager/manager.yaml
Labels: approved, lgtm, size/M

#1882 :seedling: Move Image build to GH runner
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#1885 🌱 Bump CAPI to v1.8.0
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1889 🌱 Bump CAPI to v1.8.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1890 🌱 fix verify-release.sh to understand go directive better
  hack/verify-release.sh
Labels: size/XS, approved, lgtm

#1891 🌱 bump golang to 1.22.6
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1892 🌱 bump docker/docker to v26.1.5
  test/go.mod
  test/go.sum
Labels: size/XS, approved, lgtm

#1893 🌱 bump CAPI to v1.6.8
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1909 :seedling: Bump IPAM to v1.7.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1908 :seedling: Bump IPAM to v1.6.4
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1866 🌱 Bump k8s to v1.31.0 and drop caBundle from CRDs to support Kubernetes 1.31
  config/crd/patches/webhook_in_metal3clusters.yaml
  config/crd/patches/webhook_in_metal3dataclaims.yaml
  config/crd/patches/webhook_in_metal3datas.yaml
  config/crd/patches/webhook_in_metal3datatemplates.yaml
  config/crd/patches/webhook_in_metal3machines.yaml
  config/crd/patches/webhook_in_metal3machinetemplates.yaml
  config/crd/patches/webhook_in_metal3remediations.yaml
  config/crd/patches/webhook_in_metal3remediationtemplates.yaml
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  examples/generate.sh
  hack/ensure-kubectl.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/common.go
  test/e2e/ip_reuse.go
  test/e2e/node_reuse.go
  test/e2e/upgrade_kubernetes_test.go
Labels: approved, lgtm, size/L

#1918 🌱 bump k8s.io/* deps to v0.28.13
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1919 :seedling: Bump BMO to v0.7.0-rc.0 and IPAM to v1.8.0-rc.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1888 🌱 Add CAPI v1.8 contract
  metadata.yaml
  test/e2e/data/shared/main/metadata.yaml
Labels: size/XS, approved, lgtm

#1896 🌱 Silence fetch logs and fetch manifests scripts
  scripts/fetch_manifests.sh
  scripts/fetch_target_logs.sh
Labels: size/XS, approved, lgtm

#1934 :seedling: Bump BMO to v0.8.0-rc.0
  go.mod
  go.sum
  scripts/fetch_manifests.sh
  scripts/fetch_target_logs.sh
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1924 🌱 Install setup-envtest from controller-runtime release directly and Bump envtest version to v1.31.0
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, lgtm, size/L

#1933 :seedling: Bump BMO to v0.8.0-rc.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1936 🌱 add dependabot config for release-1.8
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#1938 🌱 Adding contracts in configs for tests
  clusterctl-settings.json
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/main/metadata.yaml
Labels: size/S, approved, lgtm
