Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-03, with the labels that each got.

#1483 🌱 Remove ironic-inspector from container list for ubuntu e2e tests
  test/e2e/pivoting.go
Labels: size/XS, approved, lgtm

#1488 🌱 try fix GH workflow for image building
  .github/workflows/build-images-action.yml
Labels: size/XS, approved, lgtm

#1487 🌱 Remove ironic-inspector from container list for e2e tests
  test/e2e/cert_rotation.go
Labels: size/XS, approved, lgtm

#1492 🌱 add build images action for release-1.6
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#1494 🌱 Revert "try fix GH workflow for build images"
  .github/workflows/build-images-action.yml
Labels: size/XS, approved, lgtm

#1496 🌱 Bump golang to v1.21.7
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1497 🌱 Bump golang to v1.21.7
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1479 🐛 EnsureImage download image fix
  test/e2e/common.go
  test/go.mod
Labels: size/XS, approved, lgtm

#1498 🌱 add build images action to release-1.5
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#1503 🌱 Bump golangci-lint to v1.56.2
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  baremetal/metal3data_manager.go
  baremetal/metal3data_manager_test.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3remediation_manager_test.go
  controllers/metal3labelsync_controller_test.go
  controllers/metal3machine_controller_integration_test.go
  controllers/metal3remediation_controller.go
  hack/ensure-golangci-lint.sh
  test/e2e/cert_rotation.go
  test/e2e/common.go
  test/e2e/pivoting.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_ironic.go
Labels: approved, lgtm, size/M

#1499 🌱Bump IPAM to v1.5.3 and BMO to v0.4.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1500 🌱 Uplift IPAM to v1.6.2 and BMO to v0.5.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1502 :seedling: Add labels on e2e tests
  test/e2e/basic_integration_test.go
  test/e2e/integration_test.go
  test/e2e/ip_reuse_test.go
  test/e2e/live_iso_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: ok-to-test, approved, lgtm, size/L

#1508 🐛 bump google.golang.org/protobuf to v1.33.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1510 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: size/XS, approved, lgtm

#1514 🐛 bump google.golang.org/protobuf to v1.33.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1515 🐛 bump google.golang.org/protobuf to v1.33.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1516 🌱 add golang base image check to verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#1523 🌱 Bump CAPI to v1.6.3
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1524 🌱 Bump CAPI to v1.5.7
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1520 🌱 Bump golang to v1.21.8
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#1529 🌱 Remove release-1.2 upgrade test description from README
  README.md
Labels: size/XS, approved, lgtm

#1493 🌱 Update basic e2e trigger on README.md
  README.md
Labels: size/XS, approved, lgtm

#1543 🌱 bump k8s.io deps to v0.29.3
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#1528 🐛 e2e: Specify ip address pool for retreiving ip for accessing node
  test/e2e/common.go
  test/e2e/healthchek.go
Labels: size/S, approved, lgtm

#1525 ⚠️ Remove v1alpha5 API Version
  .golangci.yaml
  Makefile
  README.md
  api/go.mod
  api/go.sum
  api/v1alpha5/common_types.go
  api/v1alpha5/conversion.go
  api/v1alpha5/conversion_test.go
  api/v1alpha5/doc.go
  api/v1alpha5/groupversion_info.go
  api/v1alpha5/metal3cluster_types.go
  api/v1alpha5/metal3cluster_types_test.go
  api/v1alpha5/metal3data_types.go
  api/v1alpha5/metal3dataclaim_types.go
  api/v1alpha5/metal3datatemplate_types.go
  api/v1alpha5/metal3machine_types.go
  api/v1alpha5/metal3machine_types_test.go
  api/v1alpha5/metal3machinetemplate_types.go
  api/v1alpha5/metal3remediation_types.go
  api/v1alpha5/metal3remediationtemplate_types.go
  api/v1alpha5/v1alpha5_suite_test.go
  api/v1alpha5/zz_generated.conversion.go
  api/v1alpha5/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  config/crd/kustomization.yaml
  hack/codegen.sh
  main.go
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/main/metadata.yaml
  test/e2e/data/infrastructure-metal3/v0.5/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1.2/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1.3/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1.4/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1.5/metadata.yaml
  test/e2e/data/infrastructure-metal3/v1.6/metadata.yaml
  test/e2e/data/shared/main/metadata.yaml
  test/e2e/data/shared/v0.4/metadata.yaml
  test/e2e/data/shared/v1.2/metadata.yaml
  test/e2e/data/shared/v1.3/metadata.yaml
  test/e2e/data/shared/v1.4/metadata.yaml
  test/e2e/data/shared/v1.5/metadata.yaml
  test/e2e/data/shared/v1.6/metadata.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/upgrade_clusterctl_test.go
Labels: size/XXL, approved, lgtm

#1545 [release-1.5] 🐛 e2e: Specify ip address pool for retreiving ip for ssh ing node
  test/e2e/common.go
Labels: size/XS, approved, lgtm

#1560 🌱 Bump docker go module to v26.0.0
  test/e2e/pivoting.go
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1561 🌱 remove redundant make targets and scripts
  Makefile
  hack/gofmt.sh
  hack/govet.sh
Labels: ok-to-test, approved, lgtm, size/M

#1452 :seedling:Simplifying and updating clusterctl upgrade tests
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L

#1558 🌱 Fix: Metal3Data Manager log levels
  baremetal/metal3data_manager.go
Labels: size/S, ok-to-test, approved, lgtm

#1562 🌱Uplift ipam 1.7.0-beta.0 release
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#1559 :seedling: Bump cert-manager version v1.13.0 -> v1.14.0
  Tiltfile
  examples/generate.sh
  test/e2e/config/e2e_conf.yaml
Labels: ok-to-test, size/XS, approved, lgtm

#1567 🌱 support beta and rc releases in release note generator
  Makefile
  hack/tools/release/notes.go
Labels: approved, lgtm, size/M

#1563 🌱 remove ironic image related checks in verify-release.sh
  hack/verify-release.sh
Labels: size/XS, approved, lgtm

#1572 🌱 Update e2e feature tests link
  README.md
Labels: size/XS, approved, lgtm

#1571 🌱 Bump CAPI to v1.7.0-beta.1
  README.md
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1570 📖 update releasing doc
  docs/releasing.md
Labels: approved, lgtm, size/L

#1573 📖 Update e2e docs
  docs/e2e-test.md
Labels: approved, lgtm, size/M

#1574 🌱 Add lint-fix as make target
  Makefile
Labels: size/S, ok-to-test, approved, lgtm
