Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-12, with the labels that each got.

#2123 :seedling: Bump IPAM to v1.8.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2122 :seedling: Bump IPAM to v1.7.3
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2124 :seedling: Bump IPAM to v.1.9.0-beta.0
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2135 :bug: Use GOPROXY to download releases
  scripts/ci-e2e.sh
Labels: size/XS, approved, lgtm

#2125 :seedling: Bump CAPI to v1.9.0-rc.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2139 🌱 Adapt e2e test after removal of kube-rbac-proxy in BMO manifest
  test/e2e/data/bmo-deployment/overlays/release-0.8/kustomization.yaml
  test/e2e/data/bmo-deployment/overlays/release-latest/kustomization.yaml
Labels: size/XS, approved, lgtm

#2140 :seedling: Bump CAPI to v1.9.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2142 :seedling: Bump CAPI to v1.8.6
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2141 :seedling: Bump capi to v1.7.9
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2154 :seedling: Add ironic secrets files and junit e2e result file to gitignore
  .gitignore
  test/e2e/data/.gitignore
Labels: size/S, approved, lgtm

#2159 :seedling: Change broken links
  docs/api.md
  docs/dev-setup.md
  docs/e2e-test.md
Labels: size/S, approved, lgtm

#2158 :seedling: Bump k8s to v.1.32.0 and CAPI to v1.9.1
  README.md
  api/go.mod
  api/go.sum
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  examples/generate.sh
  go.mod
  go.sum
  hack/ensure-kubectl.sh
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/upgrade_clusterctl_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2156 🌱 Removes depreacted klogr.New() and rand.Seed()
  controllers/suite_test.go
  main.go
Labels: size/S, approved, lgtm

#1954 🌱 Add e2e scalability test with fake systems
  Makefile
  scripts/ci-e2e.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/fkas/kustomization.yaml
  test/e2e/data/fkas/resources.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster-with-topology/cluster-with-topology.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster-with-topology/kustomization.yaml
  test/e2e/data/infrastructure-metal3/cluster-template-centos-fake/kustomization.yaml
  test/e2e/data/infrastructure-metal3/clusterclass-metal3/clusterclass-metal3.yaml
  test/e2e/data/infrastructure-metal3/clusterclass-metal3/kustomization.yaml
  test/e2e/scalability_test.go
  test/go.mod
  test/go.sum
Labels: size/XL, approved, lgtm

#2162 :bug: bump x/crypto to v0.31.0
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2163 :bug: bump x/crypto to v0.31.0
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2170 🌱 Bump BMO to v0.9.0 and IPAM to v1.9.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2171 :seedling: Bump Golang version to 1.23.4 in FKAS Dockerfile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2165 :seedling: update dependabot config for release-1.9
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#2172 🌱 Fix FROM_K8S_VERSION variable v1.30.0 -> v1.31.2
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#2183 🌱 Set value of CAPM3RELEASE instead of relying on metal3-dev-env
  scripts/ci-e2e.sh
Labels: size/S, approved, lgtm

#2186 :seedling: Uplift BMO to v0.6.3 and IPAM to v1.7.4
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2185 :book: update build badges and triggers in README.md
  README.md
Labels: approved, lgtm, size/M
