Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2024-11, with the labels that each got.

#2066 🌱 Fix e2e healthcheck flake
  test/e2e/config/e2e_conf.yaml
  test/e2e/healthcheck.go
  test/e2e/remediation_based_feature_test.go
Labels: approved, lgtm, size/M

#2067 🌱 Uplift k8s to v1.31.2
  docs/api.md
  docs/architecture.md
  docs/dev-setup.md
  examples/generate.sh
  hack/ensure-kubectl.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2076 🌱 Bump CAPI to v1.8.5
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2083 🌱 Use controllerutils to add/remove finalizers
  baremetal/metal3cluster_manager.go
  baremetal/metal3data_manager.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  baremetal/utils.go
  baremetal/utils_test.go
Labels: approved, lgtm, size/L

#2075 🌱 Bump CAPI to v1.9.0-beta.0
  api/go.mod
  api/go.sum
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
  config/rbac/role.yaml
  controllers/metal3cluster_controller.go
  controllers/metal3data_controller.go
  controllers/metal3datatemplate_controller.go
  controllers/metal3labelsync_controller.go
  controllers/metal3machine_controller.go
  controllers/metal3machinetemplate_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: size/XXL, approved, lgtm

#2085 :bug: Add CustomDeploy to metal3machinetemplate webhook
  api/v1beta1/metal3machinetemplate_webhook.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
Labels: size/S, approved, lgtm

#2088 🌱 Uplift CAPI version for fakeapi
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
Labels: approved, lgtm, size/M

#2091 🌱 Bump Golang to 1.22.9
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#2086 :bug: bootstrap: add support for data secret
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
Labels: size/S, approved, lgtm

#2101 :seedling: simplify go version handling in verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#2087 :seedling: bump golang to 1.23.3 and golangci-lint to 1.60.3
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  baremetal/metal3cluster_manager.go
  baremetal/metal3data_manager.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  controllers/metal3cluster_controller.go
  hack/build.sh
  hack/codegen.sh
  hack/ensure-golangci-lint.sh
  hack/gomod.sh
  hack/unit.sh
  test/e2e/common.go
  test/e2e/remediation.go
Labels: approved, lgtm, size/M

#2100 :seedling: add scheduled osv-scanner workflow
  .github/workflows/osv-scanner-scan.yml
Labels: approved, lgtm, size/M

#2092 :seedling: Bump IPAM to 1.8.1
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2104 🌱 Bump CAPI to v1.9.0-beta.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2110 🌱 Use wget while downloading image
  test/e2e/common.go
Labels: size/S, approved, lgtm

#2111 🌱 Bump CAPI to v1.9.0-rc.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L
