Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-04, with the labels that each got.

#2469 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/Dockerfile
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2470 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/Dockerfile
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2468 :seedling: do not bump major version of github actions
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#2464 🌱 Enable errname, errorlint, forbidigo and perfsprint linters
  .golangci.yaml
  baremetal/metal3data_manager_test.go
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  baremetal/metal3remediation_manager.go
  baremetal/reconcile_error.go
  baremetal/reconcile_error_test.go
  baremetal/utils_test.go
  controllers/metal3remediation_controller_test.go
  main.go
  test/e2e/common.go
  test/e2e/ip_reuse.go
  test/e2e/logcollector.go
  test/e2e/md_remediations_test.go
  test/e2e/node_reuse.go
  test/e2e/pivoting.go
  test/e2e/remediation.go
  test/e2e/scalability_test.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: ok-to-test, approved, lgtm, size/L

#2462 🌱 Update e2e tests to use capi v1.10.0-beta.1 and uplift go mods to v1.10.0-beta.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/v1.10/metadata.yaml
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2484 :seedling: make osv-scanner scan run daily
  .github/workflows/osv-scanner-scan.yml
Labels: size/XS, approved, lgtm

#2483 :seedling: add labels to Dockerfile
  Dockerfile
Labels: size/S, approved, lgtm

#2493 :seedling: Bump BMO v0.10.0-beta.0 IPAM v1.10.0-beta.0 and Ginkgo v2.23.4
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2495 :rocket: Release v1.10.0-beta.0
  releasenotes/v1.10.0-beta.0.md
Labels: approved, lgtm, size/L

#2498 🌱 Set GITHUB_TOKEN in env release wf
  .github/workflows/release.yaml
Labels: size/XS, approved, lgtm

#2499 :rocket: Release v1.10.0-beta.0
  releasenotes/v1.10.0-beta.0.md
Labels: size/XS, approved, lgtm

#2501 :seedling: Enabled forcetypeassert linter
  .golangci.yaml
  baremetal/utils.go
  controllers/metal3cluster_controller.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2502 :seedling: Enabled intrange linter
  .golangci.yaml
  baremetal/metal3datatemplate_manager.go
  test/e2e/node_reuse.go
  test/e2e/upgrade_clusterctl_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: size/S, approved, lgtm

#2507 :seedling: Bump CAPI 1.10.0 and CAPM3 1.10.0-beta.0 in FKAS
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
Labels: approved, lgtm, size/L

#2500 :seedling: Enabled tagliatelle linter
  .golangci.yaml
Labels: size/S, approved, lgtm

#2521 :seedling: Enabled dupl linter
  .golangci.yaml
  baremetal/metal3data_manager.go
Labels: size/XS, approved, lgtm

#2522 :seedling: Bump IPAM 1.10.0 and BMO 0.10.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/e2e/config/e2e_conf.yaml
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2519 🐛 Handle NICs without IP addresses
  baremetal/metal3machine_manager.go
Labels: size/XS, approved, lgtm

#2531 :seedling: Bump CAPI to 1.10.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2508 :seedling: Enabled mnd linter
  .golangci.yaml
  api/v1beta1/metal3remediationtemplate_webhook.go
  baremetal/metal3data_manager.go
  baremetal/metal3machine_manager.go
  baremetal/utils.go
  controllers/metal3cluster_controller.go
  controllers/metal3labelsync_controller.go
  controllers/metal3remediation_controller.go
  hack/fake-apiserver/cmd/metal3-fkas-reconciler/main.go
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  internal/webhooks/v1beta1/metal3remediationtemplate_webhook.go
  main.go
Labels: approved, lgtm, size/L

#2530 :rocket: Release v1.10.0
  releasenotes/v1.10.0.md
Labels: approved, lgtm, size/L
