Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-05, with the labels that each got.

#2534 :seedling: Change Kubernetes version in e2e tests
  Makefile
  docs/e2e-test.md
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/S, approved, lgtm

#2536 :seedling: Add support for 1.11 in e2e
  clusterctl-settings.json
  metadata.yaml
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.10/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.10/kustimization.yaml
  test/e2e/data/infrastructure-metal3/main/metadata.yaml
  test/e2e/data/ironic-deployment/overlays/release-29.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-29.0/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-29.0/kustomization.yaml
Labels: approved, lgtm, size/L

#2548 :book: Update build badges and triggers in README.md
  README.md
Labels: approved, lgtm, size/M

#2547 :book: Update docs for release 1.10
  CONTRIBUTING.md
  README.md
  docs/e2e-test.md
Labels: approved, lgtm, size/M

#2528 🌱 E2E: Use cert-manager version from config
  test/e2e/upgrade_clusterctl_test.go
Labels: size/XS, approved, lgtm

#2556 :seedling: Fix typo in bmo deployment overlay kustomization file name
  test/e2e/data/bmo-deployment/overlays/release-0.10/kustomization.yaml
Labels: size/XS, approved, lgtm

#2544 :seedling: Enable exhaustive linter
  .golangci.yaml
  baremetal/metal3machine_manager.go
Labels: size/S, approved, lgtm

#2554 🌱 Fix ipam deploy in clusterctl tests
  baremetal/metal3machine_manager.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/ipam-metal3/v1.10/metadata.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2505 🌱Apply BMH from CAPM3 during test and skip BMH creation from dev-env
  scripts/ci-e2e.sh
  test/e2e/basic_integration_test.go
  test/e2e/common.go
  test/e2e/integration_test.go
Labels: size/S, approved, lgtm

#2560 🌱 Updating main branch clusterctl tests
  scripts/ci-e2e.sh
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/v1.10/metadata.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2570 🌱 Bump golang to v1.24
  .golangci.yaml
  Dockerfile
  Makefile
  Tiltfile
  api/go.mod
  api/go.sum
  api/v1beta1/metal3machine_types_test.go
  go.mod
  go.sum
  hack/build.sh
  hack/codegen.sh
  hack/ensure-go.sh
  hack/fake-apiserver/Dockerfile
  hack/gomod.sh
  hack/unit.sh
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L
