Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-10, with the labels that each got.

#2831 🌱Add kustomization for new ironic release-32.0
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/ironic-deployment/overlays/release-32.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-32.0/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-32.0/kustomization.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2728 🌱 Fix scalability tests
  examples/templates/clusterclass.yaml
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/main/bases/clusterclass/clusterclass.yaml
  test/e2e/data/infrastructure-metal3/main/clusterclass-metal3/clusterclass-metal3.yaml
  test/e2e/scalability_test.go
Labels: approved, lgtm, size/L

#2742 ✨ Add v1beta2 conditions for Metal3Cluster
  .golangci.yaml
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3cluster_manager.go
  baremetal/metal3machine_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  controllers/metal3cluster_controller.go
  controllers/metal3cluster_controller_integration_test.go
  controllers/metal3machine_controller.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#2845 🌱 Bump golang to v1.24.8
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2847 🌱 Bump golang to v1.24.8
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm
