Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-01, with the labels that each got.

#2211 :seedling: Bump Golang to 1.23.4
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#2201 🌱 Remove CP scaling from e2e-feature-test
  scripts/environment.sh
  test/e2e/basic_integration_test.go
  test/e2e/common.go
  test/e2e/integration_test.go
  test/e2e/ip_reuse.go
  test/e2e/ip_reuse_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: approved, lgtm, size/L

#2202 :seedling: Parameterize scalability test
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/scalability_test.go
Labels: size/S, approved, lgtm

#2209 📖 Improve e2e documentation
  docs/e2e-test.md
Labels: size/S, approved, lgtm

#2215 :seedling: Bump ipam to 1.9.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2217 :seedling: Bump IPAM to 1.8.3
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2216 :seedling: Take the new release workflow into use
  .github/workflows/release.yaml
Labels: approved, lgtm, size/L

#2214 :seedling: Bump IPAM to 1.9.2
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2232 📖 Updating docs for release 1.9
  CONTRIBUTING.md
  README.md
  docs/e2e-test.md
Labels: approved, lgtm, size/L

#2212 🌱 Fix e2e pivoting(node_reuse) test
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/M

#2235 :seedling: bump kubeconform to v0.6.7
  hack/manifestlint.sh
Labels: size/XS, approved, lgtm

#1742 ⚠️ Remove Metal3Machine owner reference from BMH
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#2203 🌱 e2e: account for ironic-standalone-operator in pivoting tests
  scripts/ci-e2e.sh
  test/e2e/cert_rotation.go
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/pivoting.go
  test/e2e/upgrade_clusterctl_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2234 :rocket: Release v1.8.4
  releasenotes/v1.8.4.md
Labels: size/S, approved, lgtm

#2239 🌱 Fix e2e pivoting(node_reuse) test
  test/e2e/config/e2e_conf.yaml
  test/e2e/node_reuse.go
  test/e2e/pivoting_based_feature_test.go
Labels: approved, lgtm, size/M

#2237 🌱 bump x/net to v0.34.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2251 :seedling: bump CAPM3 dependency in FKAS to correct branch
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
Labels: approved, lgtm, size/M

#2254 :bug: Revert "Remove Metal3Machine owner reference from BMH"
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  test/e2e/pivoting.go
Labels: approved, lgtm, size/M

#2242 🌱 Update clusterctl tests for 1.9
  docs/e2e-test.md
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/bmo-deployment/overlays/release-0.6/ironic.env
  test/e2e/data/bmo-deployment/overlays/release-0.6/kustomization.yaml
  test/e2e/data/ironic-deployment/overlays/release-25.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-25.0/keepalived_patch.yaml
  test/e2e/data/ironic-deployment/overlays/release-25.0/kustomization.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L

#2108 ✨ Deprecate NoCloudProvider and add CloudProviderEnabled
  Makefile
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3cluster_webhook.go
  api/v1beta1/metal3cluster_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3machine_manager.go
  baremetal/metal3machine_manager_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clustertemplates.yaml
  controllers/metal3cluster_controller.go
  controllers/suite_test.go
  docs/api.md
  docs/architecture.md
  examples/cluster/cluster.yaml
  examples/clusterctl-templates/clusterctl-cluster.yaml
  examples/templates/clusterclass.yaml
  test/e2e/data/infrastructure-metal3/bases/cluster/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-cluster/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-metal3/clusterclass-metal3/clusterclass-metal3.yaml
Labels: approved, lgtm, size/L

#2266 🌱 Add Peppi-lotta and Huy as reviewers
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2267 :bug: Fix live-iso serial console boot verification in e2e
  scripts/ci-e2e.sh
  test/e2e/live_iso_test.go
Labels: size/XS, approved, lgtm

#2277 🌱 E2E: Fix Ironic kustomization
  test/e2e/data/ironic-deployment/overlays/release-latest/kustomization.yaml
Labels: size/XS, approved, lgtm

#2276 🌱 remove kubebuilder:default=true for CloudProviderEnabled and set defaults in defaulting webhook
  api/v1beta1/metal3cluster_types.go
  api/v1beta1/metal3cluster_webhook.go
  api/v1beta1/metal3cluster_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3clustertemplates.yaml
Labels: size/S, approved, lgtm

#2281 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2282 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#2295 :seedling: Bump IPAM to 1.8.4
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2294 :seedling: Bump IPAM to 1.9.3
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M
