Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-03, with the labels that each got.

#2358 🌱 Bump cert-manager to v1.17.1
  Tiltfile
  examples/generate.sh
  test/e2e/config/e2e_conf.yaml
Labels: size/S, approved, lgtm

#2373 :bug: bump actions/cache to v4.2.2
  .github/workflows/dependabot.yml
Labels: size/XS, approved, lgtm

#2376 :seedling: bump golang to 1.23.7
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#2366 🌱 E2E: Adjust Ironic kustomization patch for BMO 0.8
  test/e2e/data/ironic-deployment/overlays/release-26.0/kustomization.yaml
Labels: size/XS, approved, lgtm

#2271 :bug: Fix: pulling unused images in the middle of tests
  Makefile
Labels: size/S, approved, lgtm

#2384 :seedling: Change IPAM provider name to independent Metal3 IPAM in e2e test
  test/e2e/pivoting.go
Labels: size/XS, approved, lgtm

#2385 :seedling: fix deprecation notice paragraph style
  api/v1beta1/metal3data_types.go
  api/v1beta1/metal3datatemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: size/S, approved, lgtm

#2386 :seedling: fix dependabot testing issues by re-adding "edited"
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: size/XS, approved, lgtm

#2381 🌱 E2E: Unify logging and cleanup
  test/e2e/common.go
  test/e2e/logcollector.go
  test/e2e/pivoting.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2380 🌱 E2E: Ensure cert-manager webhook is available
  .gitignore
  test/e2e/data/cert-manager-test.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2403 :bug: bump x/net, x/crypto, x/oauth2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2402 :bug: bump x/net, x/crypto and x/oauth2 go mods
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#2408 :seedling: group all github action bumps into single PR
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#2407 :seedling: bump BMO to v0.9.1
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2406 :seedling: bump BMO to v0.8.1
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2409 :seedling: bump BMO to v0.9.1
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2422 🌱 Move @mquhuy to emeritus reviewers
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2431 :seedling: bump tj-actions/changed-files to v46.0.1
  .github/workflows/release.yaml
Labels: size/XS, approved, lgtm

#2433 :seedling: update osv-scanner to v2.0.0
  .github/workflows/osv-scanner-scan.yml
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#2437 :seedling: update the used linters list
  .golangci.yaml
Labels: size/S, approved, lgtm

#2382 🌱 E2E: Install independent Metal3 IPAM after upgrade
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/cert-manager-test/certificate.yaml
  test/e2e/data/cert-manager-test/issuer.yaml
  test/e2e/data/cert-manager-test/kustomization.yaml
  test/e2e/data/cert-manager-test/namespace.yaml
  test/e2e/logcollector.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L
