Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-06, with the labels that each got.

#2582 ⚠️ Remove webhooks from api folder
  api/go.mod
  api/v1beta1/metal3cluster_webhook.go
  api/v1beta1/metal3cluster_webhook_test.go
  api/v1beta1/metal3clustertemplate_webhook.go
  api/v1beta1/metal3clustertemplate_webhook_test.go
  api/v1beta1/metal3data_webhook.go
  api/v1beta1/metal3data_webhook_test.go
  api/v1beta1/metal3dataclaim_webhook.go
  api/v1beta1/metal3dataclaim_webhook_test.go
  api/v1beta1/metal3datatemplate_webhook.go
  api/v1beta1/metal3datatemplate_webhook_test.go
  api/v1beta1/metal3machine_webhook.go
  api/v1beta1/metal3machine_webhook_test.go
  api/v1beta1/metal3machinetemplate_webhook.go
  api/v1beta1/metal3machinetemplate_webhook_test.go
  api/v1beta1/metal3remediation_webhook.go
  api/v1beta1/metal3remediation_webhook_test.go
  api/v1beta1/metal3remediationtemplate_webhook.go
  api/v1beta1/metal3remediationtemplate_webhook_test.go
Labels: size/XXL, approved, lgtm

#2583 🌱Apply BMH from CAPM3 e2e feature tests
  scripts/ci-e2e.sh
  test/e2e/common.go
  test/e2e/ip_reuse_test.go
  test/e2e/pivoting_based_feature_test.go
  test/e2e/remediation_based_feature_test.go
  test/e2e/upgrade_kubernetes_test.go
Labels: approved, lgtm, size/M

#2555 ✨ Add parameters blob for bond network interface definition
  api/go.mod
  api/v1beta1/metal3datatemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  baremetal/metal3data_manager.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: ok-to-test, approved, lgtm, size/M

#2265 :warning: Remove metal3datatemplate template reference
  baremetal/metal3datatemplate_manager.go
  baremetal/metal3datatemplate_manager_test.go
  docs/api.md
  internal/webhooks/v1beta1/metal3data_webhook.go
  test/e2e/remediation.go
Labels: kind/feature, approved, lgtm, size/L

#2594 :seedling: Use reusable link-checks and add .lycheeignore
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-link-check.yml
  .github/workflows/scheduled-link-check.yml
  .lycheeignore
Labels: approved, lgtm, size/M

#2593 🌱 Fix CONTROL_PLANE_MACHINE_COUNT and WORKER_MACHINE_COUNT for k8s upgrade and remediation test
  scripts/environment.sh
Labels: size/XS, approved, lgtm

#2597 :seedling: remove obsolete markdownlinkcheck config
  .markdownlinkcheck.json
Labels: size/S, approved, lgtm

#2599 🌱 bump cloudflare/circl to v1.6.1 in /test
  test/go.mod
  test/go.sum
Labels: size/XS, approved, lgtm

#2608 :seedling: Uplift ip-address-manager from v1.10.0 to v1.10.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/e2e/config/e2e_conf.yaml
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2609 :seedling: bump golang to 1.24.4
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2612 :rocket: Release v1.9.4
  releasenotes/v1.9.4.md
Labels: approved, lgtm, size/M

#2616 🌱 Fixing remediation tests
  test/e2e/common.go
Labels: size/S, approved, lgtm

#2535 :seedling: Uplift Kubernetes to 1.33 in envtest
  Makefile
Labels: size/XS, approved, lgtm

#2618 :seedling: Fix deleting BMHs in md_remediation
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/md_remediations_test.go
Labels: approved, lgtm, size/M

#2584 :seedling: Adopt md_rollout test from CAPI
  test/e2e/md_rollout_test.go
Labels: approved, lgtm, size/M
