Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-02, with the labels that each got.

#2304 :book: update OpenSSF CII Best Practices badge
  README.md
Labels: size/XS, approved, lgtm

#2307 🌱 Move mboukhalfa to emeritus approvers
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2296 :rocket: Release v1.9.2
  releasenotes/v1.9.2.md
Labels: approved, lgtm, size/M

#2297 :rocket: Release v1.8.5
  releasenotes/v1.8.5.md
Labels: size/S, approved, lgtm

#2298 :seedling: Bump IPAM to 1.9.3
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2312 🌱 Add miriadb image tag in release notes
  hack/tools/release/notes.go
Labels: size/XS, approved, lgtm

#2308 🌱 E2E: Adjust Ironic kustomization patch
  test/e2e/data/ironic-deployment/overlays/release-27.0/kustomization.yaml
Labels: size/XS, approved, lgtm

#2318 :seedling: workflows: sync pull_request trigger types
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: size/S, approved, lgtm

#2317 🌱 Bump k8s to v1.32.1
  docs/e2e-test.md
  examples/generate.sh
  hack/ensure-kubectl.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2320 :bug: bump golang to 1.23.6
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2323 :bug: bump golang to 1.23.6
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#2321 :seedling: pin osv-scanner image in verify-release.sh
  hack/verify-release.sh
Labels: size/XS, approved, lgtm

#2109 :seedling: Rewrite fetch_manifest.sh into golang
  test/e2e/logcollector.go
  test/e2e/pivoting.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L

#2342 🌱 Debug clusterctl upgrade test failure
  test/e2e/upgrade_clusterctl_test.go
Labels: size/XS, approved, lgtm

#2344 🌱 Bump CAPI to 1.9.5
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/e2e/scalability_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#1993 :warning: Remove IPAM deployment logic
  Makefile
  config/default/kustomization.yaml
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  config/ipam/pull_policy_patch.yaml
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#2326 :warning: Deprecate Metal3data templateReference
  api/v1beta1/metal3data_types.go
  api/v1beta1/metal3datatemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
Labels: size/S, approved, lgtm

#2346 :seedling: Bump IPAM to 1.9.4
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2345 :seedling: Bump IPAM to 1.8.5
  api/go.mod
  api/go.sum
  config/ipam/image_patch.yaml
  config/ipam/kustomization.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/S, approved, lgtm

#2348 :bug: Add use of IPAMprovider to e2e tests
  test/e2e/e2e_suite_test.go
  test/e2e/pivoting.go
Labels: size/XS, approved, lgtm

#2347 🌱 Eliminate typo in networkDataSuffix
  baremetal/metal3data_manager.go
Labels: ok-to-test, size/XS, approved, lgtm

#2357 :book: Fix broken IPAM kustomization links in releasing.md
  docs/releasing.md
Labels: size/XS, approved, lgtm

#2356 :book: Fix broken IPAM kustomization links in releasing.md
  docs/releasing.md
Labels: size/XS, approved, lgtm

#2355 :book: Remove IPAM manifests related links and check in release process
  docs/releasing.md
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#2350 :rocket: Release v1.9.3
  releasenotes/v1.9.3.md
Labels: size/S, approved, lgtm

#2349 :rocket: Release v1.8.6
  releasenotes/v1.8.6.md
Labels: size/S, approved, lgtm
