Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-09, with the labels that each got.

#2717 🐛 Delete child resources before machine
  controllers/metal3machine_controller.go
  controllers/metal3machine_controller_test.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2736 🌱 Uplift Ubuntu to 24.04
  docs/api.md
  examples/generate.sh
  scripts/environment.sh
  test/e2e/common.go
Labels: size/S, approved, lgtm

#2741 🌱 Bump CAPI to v1.11.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  scripts/ci-e2e.sh
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2743 🌱 Bump CAPI to v1.10.6
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/fake-apiserver/go.mod
  hack/fake-apiserver/go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M

#2760 📖 Add Alpha release in release documentation
  docs/releasing.md
Labels: size/XS, approved, lgtm

#2798 :book: Update trigger doc, build badges, support matrix
  README.md
Labels: approved, lgtm, size/L

#2820 :seedling: Add logging to releaseAddressFromM3Pool function
  baremetal/metal3data_manager.go
Labels: size/XS, approved, lgtm

#2818 🌱 Change interface names to predictable ones for Centos
  examples/generate.sh
  hack/ensure-kubectl.sh
  hack/gen_tilt_settings.sh
  scripts/environment.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure-metal3/bases/centos-kubeadm-config/centos-kubeadm-config.yaml
  test/e2e/data/infrastructure-metal3/bases/clusterclass-centos-kubeadm-config/clusterclass-centos-kubeadm-config.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/scalability_test.go
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/M

#2737 :seedling: Enable testing with CAPI nightly builds
  docs/e2e-test.md
  scripts/ci-e2e.sh
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/capi/v1.12/metadata.yaml
  test/e2e/upgrade_clusterctl_test.go
Labels: approved, lgtm, size/L

#2799 :seedling: Fix OSV-Scanner
  .github/workflows/osv-scanner-scan.yml
  .github/workflows/scheduled-osv-scan.yml
Labels: approved, lgtm, size/M

#2824 :seedling: remove osv-scanner from release branches
  .github/workflows/osv-scanner-scan.yml
Labels: approved, lgtm, size/M

#2829 :seedling: add specific time to dependabot config
  .github/dependabot.yml
Labels: size/S, approved, lgtm

#2830 🌱 cmd: strip out symbol table & DWARF debugging info
  Dockerfile
  Makefile
Labels: size/S, approved, lgtm
