Repository metal3-io/cluster-api-provider-metal3, pull requests merged in 2025-08, with the labels that each got.

#2679 :rocket: Release v1.11.0-alpha.0
  releasenotes/v1.11.0-alpha.0.md
Labels: approved, lgtm, size/L

#2680 🌱 Fix small typo in verify release
  hack/verify-release.sh
Labels: size/XS, approved, lgtm

#2683 🌱 Fix remediation test
  test/e2e/healthcheck.go
Labels: size/XS, approved, lgtm

#2690 :seedling: bump golang to 1.24.6
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2692 :seedling: bump golang to 1.24.6
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2693 :seedling: bump golang to 1.24.6
  Dockerfile
  Makefile
  hack/fake-apiserver/Dockerfile
Labels: size/XS, approved, lgtm

#2695 🌱 Add continue-on-error and improve Slack notifications for osv-scanner
  .github/workflows/osv-scanner-scan.yml
Labels: size/XS, approved, lgtm

#2696 :seedling: Uplift Ubuntu to 24.04
  docs/api.md
  examples/generate.sh
  scripts/environment.sh
  test/e2e/common.go
Labels: size/S, approved, lgtm

#2718 🌱 Add IPA_BASEURI in ironic config to fix IPA download from cache
  test/e2e/data/ironic-deployment/overlays/pr-test/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-26.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-27.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-29.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
Labels: size/XS, approved, lgtm

#2731 🌱 Add IPA_BASEURI in ironic config to fix IPA download for release-1.9
  test/e2e/data/ironic-deployment/overlays/release-25.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-26.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
Labels: size/XS, approved, lgtm

#2730 🌱Add IPA_BASEURI in ironic config to fix IPA download for release-1.10
  test/e2e/data/ironic-deployment/overlays/pr-test/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-26.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-27.0/ironic_bmo_configmap.env
  test/e2e/data/ironic-deployment/overlays/release-latest/ironic_bmo_configmap.env
Labels: size/XS, approved, lgtm
